[Driver][clang-offload-bundler] Add asserts requirement for test relying on debug build
intel/llvm pull request #10379
Opened 2023-07-14 03:49 UTC by asudarsa

This PR addresses https://github.com/intel/llvm/issues/10238

Thanks

2023-07-14 15:50 UTC, mdtoguchi approved these changes

2023-07-20 14:54 UTC, asudarsa commented
Sorry. some reviewers got added due to an intermediate 'buggy' merge. 

Thanks

2023-07-22 00:05 UTC, bader reviewed
I suggest we reset this file to the original state from main branch - https://github.com/intel/llvm/blob/main/clang/test/Driver/clang-offload-bundler-standardize.c. 
Otherwise, there will be conflicts with the community changes.
I think there should be no SYCL specific changes in this file. Am I right?

2023-07-31 22:19 UTC, asudarsa commented
> I suggest we reset this file to the original state from main branch - https://github.com/intel/llvm/blob/main/clang/test/Driver/clang-offload-bundler-standardize.c. Otherwise, there will be conflicts with the community changes. I think there should be no SYCL specific changes in this file. Am I right?

Ah.. I did not follow that we had a dedicated 'main' branch. I thought 'sycl' was our 'main' branch. 
I can reset this file to be in sync   with the 'main' copy.   
Just  curious,  do we have to always try to be in sync with 'main' branch when possible?

Thanks

2023-07-31 22:44 UTC, bader commented
> Just curious, do we have to always try to be in sync with 'main' branch when possible?

Yes. `main` is a mirror of https://github.com/llvm/llvm-project/tree/main branch and we need to the difference between `main` and `sycl` branches as minimal as possible to avoid conflicts during pulldown process. We can do this by upstreaming SYCL patches to the https://github.com/llvm/llvm-project/tree/main and avoid unnecessary changes in the `sycl` branch.

2023-08-01 20:50 UTC, asudarsa commented
> > Just curious, do we have to always try to be in sync with 'main' branch when possible?
> 
> Yes. `main` is a mirror of https://github.com/llvm/llvm-project/tree/main branch and we need to the difference between `main` and `sycl` branches as minimal as possible to avoid conflicts during pulldown process. We can do this by upstreaming SYCL patches to the https://github.com/llvm/llvm-project/tree/main and avoid unnecessary changes in the `sycl` branch.

Thanks for the clarification @bader.
In this case, the only difference is the main branch has '// REQUIRES: asserts' added twice. May be the main branch needs to be fixed?

Thanks

2023-08-01 20:59 UTC, bader commented
> > > Just curious, do we have to always try to be in sync with 'main' branch when possible?
> > 
> > 
> > Yes. `main` is a mirror of https://github.com/llvm/llvm-project/tree/main branch and we need to the difference between `main` and `sycl` branches as minimal as possible to avoid conflicts during pulldown process. We can do this by upstreaming SYCL patches to the https://github.com/llvm/llvm-project/tree/main and avoid unnecessary changes in the `sycl` branch.
> 
> Thanks for the clarification @bader. In this case, the only difference is the main branch has '// REQUIRES: asserts' added twice. May be the main branch needs to be fixed?
> 
> Thanks

That's an option as well. The final goal is the have the same version of the file in both branches.

2023-09-12 03:12 UTC, bader requested changes
@asudarsa, please, resolve merge conflicts.

2024-08-02 15:34 UTC, maarquitos14 commented
I think this PR can be closed: the changes made here seem to be already made in the current status of the file. Please, @asudarsa close if you agree.

2025-03-01 02:05 UTC, closed without merging