fix a bug in property check
intel/llvm pull request #10685
Opened 2023-08-03 21:01 UTC by broxigarchen

Fixed a bug in FPGA annotated property check such that the logic should be 'or' instead of 'and'

2023-08-03 22:03 UTC, dm-vodopyanov commented
Can you please add a test?

2023-08-09 19:58 UTC, broxigarchen commented
> Can you please add a test?

There is a test source using this. This PR also fix it

2023-08-10 10:39 UTC, dm-vodopyanov approved these changes

2023-08-11 18:03 UTC, broxigarchen commented
@intel/llvm-gatekeepers can you help to take a look at this? Thanks!

2023-08-11 19:20 UTC, tiwaria1 requested changes
Requested a test change

2023-08-11 19:20 UTC, tiwaria1 commented on sycl/test/extensions/annotated_arg/annotated_arg_for_ptr.cpp
Please add a line that checks that using alignment on annotated_ptr without buffer location does NOT error out.

2023-08-14 18:58 UTC, tiwaria1 approved these changes

2023-08-14 22:15 UTC, broxigarchen commented
> @intel/llvm-gatekeepers can you help to take a look at this? Thanks!

Gentle ping again!

2023-08-15 09:53 UTC, steffenlarsen commented
ESIMD Timed Out Tests (1):
  SYCL :: Prefix_Local_sum3.cpp - Unrelated. Expected to be a hiccup.

2023-08-15 09:53 UTC, merged