[SYCL][Matrix] Making PVC tf32 test cases pass on PVC and removed the XMX8 TF32 test cases as they are not supported.
intel/llvm pull request #10980
Opened 2023-08-27 14:48 UTC by arnamoy10

2023-08-28 17:40 UTC, YuriPlyakhin requested changes

2023-08-28 17:40 UTC, YuriPlyakhin commented on sycl/test-e2e/Matrix/joint_matrix_tf32.cpp
> +// XFAIL:CPU
AFAIK, this check is case-sensitive
```suggestion
// XFAIL:cpu
```

2023-08-30 14:20 UTC, arnamoy10 commented on sycl/test-e2e/Matrix/joint_matrix_tf32.cpp
> +// XFAIL:CPU
Thanks, done

2023-08-30 18:29 UTC, YuriPlyakhin approved these changes
LGTM

2023-08-30 19:08 UTC, aelovikov-intel commented
> @intel/llvm-gatekeepers Help merge please? I think the error is due to removal of two existing files, which is giving rise to conflicts.

You have to resolve the conflicts first.

2023-08-31 13:29 UTC, arnamoy10 commented
> > @intel/llvm-gatekeepers Help merge please? I think the error is due to removal of two existing files, which is giving rise to conflicts.
> 
> You have to resolve the conflicts first.

@aelovikov-intel Conflicts resolved.  The failure seems non-related.  Help merge please?

2023-08-31 13:56 UTC, steffenlarsen commented
HIP failures reported in https://github.com/intel/llvm/issues/10460.

2023-08-31 13:56 UTC, merged