[SYCL][COMPAT] Added constant memory_region for read_only memory
intel/llvm pull request #11024
Opened 2023-08-31 10:38 UTC by Alcpz

This PR extends the memory wrapper of SYCLcompat to support allocating read only memory.

To allow the allocation of `device_memory` directly for source to source translation:
- Extended `device_memory` to support a queue parameter in its constructor, which defaults to `syclcompat::get_default_queue`
- Added device_read_only property to device memory if usm device read only extension is available for `memory_region::constant`

Documentation was already updated, except for the usm device read only extension

2023-08-31 21:17 UTC, joeatodd requested changes
Some issues with the tests I think.

2023-08-31 21:17 UTC, joeatodd commented on sycl/test-e2e/syclcompat/memory/memory_management_test2.cpp
> +      });
Is it appropriate to be writing to `syclcompat::constant_memory`?

2023-08-31 21:17 UTC, joeatodd commented on sycl/test-e2e/syclcompat/memory/memory_management_test3.cpp
> +  }
As in other file, this is duplicate?

2023-08-31 21:17 UTC, joeatodd commented on sycl/test-e2e/syclcompat/memory/memory_management_test3.cpp
> +  std::cout << __PRETTY_FUNCTION__ << std::endl;
Since the `constant_memcpy` tests here are similar to those in `memory_management_test1.cpp`, the comments I left there also apply here.

2023-09-06 09:31 UTC, Alcpz commented on sycl/test-e2e/syclcompat/memory/memory_management_test1.cpp
> +  syclcompat::memcpy((void *)d_A.get_ptr(), (void *)&h_A[0],
This was addressed. I also removed the unnecessary `(void *)` casts

2023-09-06 09:31 UTC, Alcpz commented on sycl/test-e2e/syclcompat/memory/memory_management_test1.cpp
> +  }
Yes, this error was inherited and I missed it completely, thanks for spotting this.

2023-09-06 11:17 UTC, joeatodd approved these changes

2023-09-06 13:08 UTC, Alcpz commented
@intel/llvm-gatekeepers We think this is ready to merge, Thanks!

2023-09-07 13:26 UTC, Alcpz commented
@intel/llvm-gatekeepers We think this is ready to merge, Thanks!

2023-09-07 13:48 UTC, merged