[SYCL][Graph] Add support for CUDA backend
intel/llvm pull request #11133
Opened 2023-09-11 10:44 UTC by mfrancepillois

Adds support for enabling CUDA backend with Sycl-Graph:

- Implements CommandBuffer functions for the cuda backend using Cuda Driver API and CudaGraph to group operations.
- Fixes a CommandBuffer bug in the CUDA pluging initialization.
- Reports CUDA backend as supported for the graph extension.
- Adds support for memory copy operations for CUDA backend
- Enables Graph e2e tests with CUDA backend.

2023-10-18 13:49 UTC, Bensuo commented
CI fails appear to be unrelated, as seen in other PRs, for example here: https://github.com/intel/llvm/pull/11553#issuecomment-1766717083

2023-10-31 13:25 UTC, kbenzie requested changes

2023-10-31 13:25 UTC, kbenzie commented on sycl/plugins/unified_runtime/CMakeLists.txt
> +  set(UNIFIED_RUNTIME_TAG 5ecaf66a2d0325cb9b8cfcb8e39a60810fa46cc2)
Now that https://github.com/oneapi-src/unified-runtime/pull/932 has merged please update `UNIFIED_RUNTIME_TAG` as follows and pull in the latest sycl branch changes. This should then be ready to take out of draft.

```suggestion
  set(UNIFIED_RUNTIME_REPO "https://github.com/oneapi-src/unified-runtime.git")
  # commit be53fb3ba5bf1ac33051456d72c61b6a01d94a72
  # Merge: 55d432c 5ecaf66
  # Author: Kenneth Benzie (Benie) <k.benzie@codeplay.com>
  # Date:   Tue Oct 31 13:22:52 2023 +0000
  #     Merge pull request #932 from Bensuo/cuda-cmd-buffers
  #     [CUDA][EXP] CUDA adapter support for command buffers
```

2023-10-31 15:00 UTC, EwanC commented
Could we double check this covers all the Graphs E2E tests that've been added since this PR was opened, e.g.
* https://github.com/intel/llvm/pull/11418
* https://github.com/intel/llvm/pull/11505/

2023-10-31 15:41 UTC, kbenzie approved these changes
UR LGTM

2023-11-01 17:05 UTC, kbenzie approved these changes
UR LGTM

2023-11-01 19:51 UTC, reble commented on sycl/doc/design/CommandGraph.md
> +Synchonizations between commands (UR sync-points) are implemented
```suggestion
Synchronization between commands (UR sync-points) is implemented by
```

2023-11-01 19:52 UTC, reble commented on sycl/doc/design/CommandGraph.md
> +An executable CUDA Graph, which contains all commands and synchonization
```suggestion
An executable CUDA Graph, which contains all commands and synchronization
```

2023-11-01 19:55 UTC, reble commented on sycl/doc/design/CommandGraph.md
> +the SYCL Graph backend to remain consistent with other UR functions.
Can we add a brief statement, why that is the case?

2023-11-01 20:24 UTC, reble commented on sycl/doc/design/images/SYCL-Graph-Architecture.svg
Let's make the HW specific layer consistent and add Intel to the CPU, GPU, FPGA, ... box.

2023-11-02 12:06 UTC, Bensuo approved these changes

2023-11-02 12:34 UTC, kbenzie commented
@intel/llvm-reviewers-runtime please review ASAP, this is blocking other UR changes.

2023-11-03 09:43 UTC, EwanC commented
@intel/llvm-reviewers-runtime Could you give this PR a look please

2023-11-03 09:47 UTC, steffenlarsen approved these changes
Sorry, this one flew under my radar! LGTM!

2023-11-03 09:47 UTC, merged