[OpenMP][Doc] Fix OMP documentation link in the root directory
intel/llvm pull request #11165
Opened 2023-09-13 14:20 UTC by AGindinson

Replace the outdated branch link: redirect to the active OpenMP subfolder
instead.

Signed-off-by: Artem Gindinson <artem.gindinson@intel.com>

2023-09-13 15:40 UTC, bader requested changes
@AGindinson, why would we want this change?
The link is supposed to refer to a branch, not sub-project.

2023-09-13 15:47 UTC, AGindinson commented
> @AGindinson, why would we want this change? The link is supposed to refer to the branch, not OpenMP sub-project.

@bader, my reasoning has been as follows:
- currently, the link appears to be pointing to https://github.com/intel/llvm/blob/sycl/tree/openmp (which is a 404) instead of the intended https://github.com/intel/llvm/tree/openmp
- the `openmp` branch itself hasn't been updated [since 2021](https://github.com/intel/llvm/commits/openmp) and doesn't highlight any unique information, at least in the root README.

2023-09-13 16:17 UTC, bader commented
> > @AGindinson, why would we want this change? The link is supposed to refer to the branch, not OpenMP sub-project.
> 
> @bader, my reasoning has been as follows:
> 
> * currently, the link appears to be pointing to https://github.com/intel/llvm/blob/sycl/tree/openmp (which is a 404) instead of the intended https://github.com/intel/llvm/tree/openmp
> * the `openmp` branch itself hasn't been updated [since 2021](https://github.com/intel/llvm/commits/openmp) and doesn't highlight any unique information, at least in the root README.

I don't get it. This link is supposed to is refer to the branch for "Late-outline OpenMP\* and OpenMP\* Offload". I agree that the branch might be outdated but changing the link to the OpenMP sub-project in the `sycl` branch doesn't make sense. According to my understanding the sub-project has nothing to do with "Late-outline OpenMP\* and OpenMP\* Offload".

@stdale-intel, could you check with the OpenMP team if https://github.com/intel/llvm/tree/openmp is still needed, please? If no, I suggest we just remove this section from the README file.

2023-09-15 22:56 UTC, stdale-intel commented
> > > @AGindinson, why would we want this change? The link is supposed to refer to the branch, not OpenMP sub-project.
> > 
> > 
> > @bader, my reasoning has been as follows:
> > 
> > * currently, the link appears to be pointing to https://github.com/intel/llvm/blob/sycl/tree/openmp (which is a 404) instead of the intended https://github.com/intel/llvm/tree/openmp
> > * the `openmp` branch itself hasn't been updated [since 2021](https://github.com/intel/llvm/commits/openmp) and doesn't highlight any unique information, at least in the root README.
> 
> I don't get it. This link is supposed to is refer to the branch for "Late-outline OpenMP* and OpenMP* Offload". I agree that the branch might be outdated but changing the link to the OpenMP sub-project in the `sycl` branch doesn't make sense. According to my understanding the sub-project has nothing to do with "Late-outline OpenMP* and OpenMP* Offload".
> 
> @stdale-intel, could you check with the OpenMP team if https://github.com/intel/llvm/tree/openmp is still needed, please? If no, I suggest we just remove this section from the README file.

I actually think we should not make this change. We have some other edits coming to readme.md and I plan to also cover this as part of that. all in all, I am in agreement with @bader , this edit in itself doesn't make sense. and should not be done.

2023-09-16 04:24 UTC, AGindinson commented
Got it, thanks! Please consider the whole thing as a heads-up regarding the invalid link :)

2023-09-16 04:24 UTC, closed without merging