[SYCL][JM tests] fix syntax error for LIT
intel/llvm pull request #11384
Opened 2023-10-02 20:32 UTC by dkhaldi

2023-10-02 20:35 UTC, YuriPlyakhin approved these changes
LGTM

2023-10-03 17:55 UTC, dkhaldi commented
@intel/llvm-gatekeepers, the failure seems generic, I created an issue in https://github.com/intel/llvm/issues/11405.
If you agree, can you help merge?

2023-10-03 21:46 UTC, YuriPlyakhin requested changes

2023-10-03 21:46 UTC, YuriPlyakhin commented on sycl/test-e2e/Matrix/SG32/joint_matrix_bf16_fill_k_cache_unroll.cpp
>  // XFAIL: gpu
// RUN: %{build} -mllvm -inline-threshold=5000 -o %t_gpu.out -DSYCL_EXT_ONEAPI_MATRIX_VERSION=4 -DMANUAL_UNROLL
// RUN: %{build} -mllvm -inline-threshold=5000 -o %t_cpu.out -DSYCL_EXT_ONEAPI_MATRIX_VERSION=4 -DMANUAL_UNROLL -DtM=16 -DtK=32 -DNCACHE1=32 -DKCACHE1=32

// RUN: %if gpu %{ %{run} %t_gpu.out %}
// RUN: %if cpu %{ %{run} %t_cpu.out %}

2023-10-03 21:46 UTC, YuriPlyakhin commented on sycl/test-e2e/Matrix/SG32/joint_matrix_bf16_fill_k_cache_unroll.cpp
>  // XFAIL: gpu
Hi @dkhaldi , I checked that adding %} at the end is not enough to fix these tests.
if gpu/if cpu doesn't work for builds, so we should build for gpu and cpu unconditionally.
Then run either cpu or gpu, when condition satisfied.
Also, please, remote xfail:gpu.
See the code I inserted above

2023-10-03 21:46 UTC, YuriPlyakhin commented on sycl/test-e2e/Matrix/SG32/joint_matrix_bf16_fill_k_cache_unroll.cpp
>  // XFAIL: gpu
The same should be applied for all 4 tests.

2023-10-04 21:31 UTC, YuriPlyakhin approved these changes
LGTM

2023-10-05 03:11 UTC, YuriPlyakhin commented
@intel/llvm-gatekeepers , please, merge, all green

2023-10-05 05:19 UTC, merged