wip
intel/llvm pull request #11406
Opened 2023-10-03 19:44 UTC by YuriPlyakhin

2023-10-11 13:07 UTC, dkhaldi requested changes
Are the changes in Legacy necessary as these use short instead of bfloat16 to represent bfloat16 type?

2023-10-13 23:42 UTC, YuriPlyakhin commented
> Are the changes in Legacy necessary as these use short instead of bfloat16 to represent bfloat16 type?

Yes, changes in Legacy folder are also necessary, since tests there are using fabs without namespace as well.
I did not find where do you see usage of short in my changes. make_fp32 which I removed from Legacy tests and replaced with common.hpp seems to be identical.

2023-10-13 23:52 UTC, YuriPlyakhin commented on sycl/test-e2e/Matrix/Legacy/joint_matrix_bfloat16_colmajorA_colmajorB.cpp
> -#include <iostream>
resolved

2023-10-16 14:36 UTC, dkhaldi approved these changes
LGTM

2023-10-16 16:31 UTC, YuriPlyakhin commented
@intel/llvm-gatekeepers , all green, please, merge

2023-10-16 16:32 UTC, merged