Manual sycl rebase
intel/llvm pull request #11402
Opened 2023-10-03 16:13 UTC by victor-eds

DO NOT SQUASH AND MERGE THIS PR

5fcbc3572f7b1495489afd4a0cc706b3003dc6e9 reduces changes to those needed by SYCL-MLIR

818c2e699788e400c8344ecd35e9f5f629f3f9db is a fix to handle new types in headers

2023-10-03 16:14 UTC, victor-eds commented
Draft, as it depends on #11401

2023-10-03 16:15 UTC, victor-eds commented
Note: Before merging, fix rebase commit message link

2023-10-03 16:15 UTC, victor-eds commented
Diff after change:

```diff
diff --git a/sycl/CMakeLists.txt b/sycl/CMakeLists.txt
index ffe3bac291a2..5fb9f97ddb8c 100644
--- a/sycl/CMakeLists.txt
+++ b/sycl/CMakeLists.txt
@@ -329,6 +329,7 @@ endif()
 # SYCL toolchain builds all components: compiler, libraries, headers, etc.
 add_custom_target(sycl-compiler
   DEPENDS append-file
+          cgeist
           clang
           clang-offload-wrapper
           clang-offload-bundler
@@ -343,6 +344,7 @@ add_custom_target(sycl-compiler
           llvm-spirv
           llvm-link
           llvm-objcopy
+          mlir-translate
           spirv-to-ir-wrapper
           sycl-post-link
           opencl-aot
@@ -418,6 +420,7 @@ get_property(SYCL_TOOLCHAIN_DEPS GLOBAL PROPERTY SYCL_TOOLCHAIN_INSTALL_COMPONEN
 set( SYCL_TOOLCHAIN_DEPLOY_COMPONENTS
      append-file
      boost_mp11-headers
+     cgeist
      clang
      clang-offload-wrapper
      clang-offload-bundler
diff --git a/sycl/include/sycl/detail/defines_elementary.hpp b/sycl/include/sycl/detail/defines_elementary.hpp
index 999a103c00f9..556568ceffbf 100644
--- a/sycl/include/sycl/detail/defines_elementary.hpp
+++ b/sycl/include/sycl/detail/defines_elementary.hpp
@@ -78,5 +78,11 @@
 #endif
 #endif
 
+#ifdef __clang__
+#define __SYCL_ANNOTATE(str) __attribute__((annotate(#str)))
+#else
+#define __SYCL_ANNOTATE(str)
+#endif
+
 static_assert(__cplusplus >= 201703L,
               "DPCPP does not support C++ version earlier than C++17.");
diff --git a/sycl/include/sycl/handler.hpp b/sycl/include/sycl/handler.hpp
index a99f1138a8e2..1baf3882f790 100644
--- a/sycl/include/sycl/handler.hpp
+++ b/sycl/include/sycl/handler.hpp
@@ -886,9 +886,10 @@ private:
     if (KernelHasName) {
       // TODO support ESIMD in no-integration-header case too.
       MArgs.clear();
+      auto numParams __SYCL_ANNOTATE(kernel_num_params) = KI::getNumParams();
+      auto *paramDesc __SYCL_ANNOTATE(kernel_param_desc) = &KI::getParamDesc(0);
       extractArgsAndReqsFromLambda(reinterpret_cast<char *>(KernelPtr),
-                                   KI::getNumParams(), &KI::getParamDesc(0),
-                                   KI::isESIMD());
+                                   numParams, paramDesc, KI::isESIMD());
       MKernelName = KI::getName();
     } else {
       // In case w/o the integration header it is necessary to process
@@ -1217,8 +1218,9 @@ private:
   template <typename KernelName, typename KernelType, int Dims,
             typename PropertiesT =
                 ext::oneapi::experimental::detail::empty_properties_t>
-  void parallel_for_lambda_impl(range<Dims> UserRange, PropertiesT Props,
-                                KernelType KernelFunc) {
+  __SYCL_ALWAYS_INLINE void parallel_for_lambda_impl(range<Dims> UserRange,
+                                                     PropertiesT Props,
+                                                     KernelType KernelFunc) {
     throwIfActionIsCreated();
     throwOnLocalAccessorMisuse<KernelName, KernelType>();
     if (!range_size_fits_in_size_t(UserRange))
@@ -1310,8 +1312,9 @@ private:
   /// \param KernelFunc is a SYCL kernel function.
   template <typename KernelName, typename KernelType, int Dims,
             typename PropertiesT>
-  void parallel_for_impl(nd_range<Dims> ExecutionRange, PropertiesT Props,
-                         _KERNELFUNCPARAM(KernelFunc)) {
+  __SYCL_ALWAYS_INLINE void parallel_for_impl(nd_range<Dims> ExecutionRange,
+                                              PropertiesT Props,
+                                              _KERNELFUNCPARAM(KernelFunc)) {
     throwIfActionIsCreated();
     // TODO: Properties may change the kernel function, so in order to avoid
     //       conflicts they should be included in the name.
@@ -1355,7 +1358,8 @@ private:
   /// \param NumWorkItems is a range defining indexing space.
   /// \param Kernel is a SYCL kernel function.
   template <int Dims>
-  void parallel_for_impl(range<Dims> NumWorkItems, kernel Kernel) {
+  __SYCL_ALWAYS_INLINE void parallel_for_impl(range<Dims> NumWorkItems,
+                                              kernel Kernel) {
     throwIfActionIsCreated();
     MKernel = detail::getSyclObjImpl(std::move(Kernel));
     detail::checkValueRange<Dims>(NumWorkItems);
@@ -1417,10 +1421,9 @@ private:
   template <typename KernelName, typename KernelType, int Dims,
             typename PropertiesT =
                 ext::oneapi::experimental::detail::empty_properties_t>
-  void parallel_for_work_group_lambda_impl(range<Dims> NumWorkGroups,
-                                           range<Dims> WorkGroupSize,
-                                           PropertiesT Props,
-                                           _KERNELFUNCPARAM(KernelFunc)) {
+  __SYCL_ALWAYS_INLINE void parallel_for_work_group_lambda_impl(
+      range<Dims> NumWorkGroups, range<Dims> WorkGroupSize, PropertiesT Props,
+      _KERNELFUNCPARAM(KernelFunc)) {
     throwIfActionIsCreated();
     // TODO: Properties may change the kernel function, so in order to avoid
     //       conflicts they should be included in the name.
@@ -1885,21 +1888,27 @@ public:
   }
 
   template <typename KernelName = detail::auto_name, typename KernelType>
-  void parallel_for(range<1> NumWorkItems, _KERNELFUNCPARAM(KernelFunc)) {
+  __SYCL_ALWAYS_INLINE void
+  parallel_for(range<1> NumWorkItems __SYCL_ANNOTATE(range),
+               _KERNELFUNCPARAM(KernelFunc) __SYCL_ANNOTATE(kernel)) {
     parallel_for_lambda_impl<KernelName>(
         NumWorkItems, ext::oneapi::experimental::detail::empty_properties_t{},
         std::move(KernelFunc));
   }
 
   template <typename KernelName = detail::auto_name, typename KernelType>
-  void parallel_for(range<2> NumWorkItems, _KERNELFUNCPARAM(KernelFunc)) {
+  __SYCL_ALWAYS_INLINE void
+  parallel_for(range<2> NumWorkItems __SYCL_ANNOTATE(range),
+               _KERNELFUNCPARAM(KernelFunc) __SYCL_ANNOTATE(kernel)) {
     parallel_for_lambda_impl<KernelName>(
         NumWorkItems, ext::oneapi::experimental::detail::empty_properties_t{},
         std::move(KernelFunc));
   }
 
   template <typename KernelName = detail::auto_name, typename KernelType>
-  void parallel_for(range<3> NumWorkItems, _KERNELFUNCPARAM(KernelFunc)) {
+  __SYCL_ALWAYS_INLINE void
+  parallel_for(range<3> NumWorkItems __SYCL_ANNOTATE(range),
+               _KERNELFUNCPARAM(KernelFunc) __SYCL_ANNOTATE(kernel)) {
     parallel_for_lambda_impl<KernelName>(
         NumWorkItems, ext::oneapi::experimental::detail::empty_properties_t{},
         std::move(KernelFunc));
@@ -1931,8 +1940,10 @@ public:
   template <typename KernelName = detail::auto_name, typename KernelType,
             int Dims>
   __SYCL2020_DEPRECATED("offsets are deprecated in SYCL2020")
-  void parallel_for(range<Dims> NumWorkItems, id<Dims> WorkItemOffset,
-                    _KERNELFUNCPARAM(KernelFunc)) {
+  __SYCL_ALWAYS_INLINE
+      void parallel_for(range<Dims> NumWorkItems __SYCL_ANNOTATE(range),
+                        id<Dims> WorkItemOffset __SYCL_ANNOTATE(offset),
+                        _KERNELFUNCPARAM(KernelFunc) __SYCL_ANNOTATE(kernel)) {
     throwIfActionIsCreated();
     using NameT =
         typename detail::get_kernel_name_t<KernelName, KernelType>::name;
@@ -2013,15 +2024,21 @@ public:
     MKernelName = getKernelName();
   }
 
-  void parallel_for(range<1> NumWorkItems, kernel Kernel) {
+  __SYCL_ALWAYS_INLINE void
+  parallel_for(range<1> NumWorkItems __SYCL_ANNOTATE(range),
+               kernel Kernel __SYCL_ANNOTATE(kernel)) {
     parallel_for_impl(NumWorkItems, Kernel);
   }
 
-  void parallel_for(range<2> NumWorkItems, kernel Kernel) {
+  __SYCL_ALWAYS_INLINE void
+  parallel_for(range<2> NumWorkItems __SYCL_ANNOTATE(range),
+               kernel Kernel __SYCL_ANNOTATE(kernel)) {
     parallel_for_impl(NumWorkItems, Kernel);
   }
 
-  void parallel_for(range<3> NumWorkItems, kernel Kernel) {
+  __SYCL_ALWAYS_INLINE void
+  parallel_for(range<3> NumWorkItems _ [...]

2023-10-04 14:22 UTC, jopperm approved these changes

2023-10-04 14:25 UTC, whitneywhtsang approved these changes

2023-10-04 15:21 UTC, whitneywhtsang requested changes
There are TIMEOUTs, we cannot merge this in until that is understood.

2023-10-10 01:56 UTC, whitneywhtsang approved these changes

2023-10-10 01:57 UTC, merged