[Matrix] make joint_matrix_transposeC_impl.hpp simpler: just joint_matrix_load&joint_matrix_store for colC
intel/llvm pull request #11604
Opened 2023-10-19 16:16 UTC by yubingex007-a11y

2023-10-19 16:18 UTC, yubingex007-a11y commented
I think we can merge this PR after my backend patch is merged

2023-10-19 16:46 UTC, dkhaldi approved these changes
LGTM

2023-10-19 18:27 UTC, YuriPlyakhin requested changes

2023-10-19 18:28 UTC, YuriPlyakhin commented
Also should XFAIL be updated here as well? SG32/joint_matrix_transposeC.cpp

2023-10-25 03:42 UTC, yubingex007-a11y commented
ping @YuriPlyakhin

2023-10-25 11:19 UTC, yubingex007-a11y commented on sycl/test-e2e/Matrix/joint_matrix_transposeC_impl.hpp
> +  auto pA = multi_ptr<T2, sycl::access::address_space::global_space>(A);
done

2023-10-25 11:19 UTC, yubingex007-a11y commented on sycl/test-e2e/Matrix/joint_matrix_transposeC_impl.hpp
> +  auto pB = multi_ptr<T2, sycl::access::address_space::global_space>(B);
done

2023-10-25 11:20 UTC, yubingex007-a11y commented on sycl/test-e2e/Matrix/joint_matrix_transposeC_impl.hpp
>    matrix_multiply<float, bfloat16, MATRIX_M, MATRIX_K, MATRIX_K / vnniFactor,
done

2023-10-25 11:20 UTC, yubingex007-a11y commented
> Also should XFAIL be updated in SG32/joint_matrix_transposeC.cpp as well?

done

2023-10-25 18:49 UTC, YuriPlyakhin approved these changes
LGTM

2023-10-25 18:49 UTC, YuriPlyakhin commented
@intel/llvm-gatekeepers , all green, please, merge

2023-10-25 18:55 UTC, merged