[SYCL] Error for conduit and register_map on annotated_arg/ptr
intel/llvm pull request #11711
Opened 2023-10-30 19:24 UTC by yug-intel

This change ensures that there is an error when the user tries to specify both the `conduit` property and the `register_map` property on `annotated_arg` or `annotated_ptr`. 

For example, the following variable: 

```cpp
annotated_arg<int, decltype(properties{conduit, register_map})> a;
```

will generate the following assertion failure: 

```
error: static assertion failed due to requirement 'detail::hasConduitAndRegisterMap<sycl::ext::oneapi::experimental::property_value<sycl::ext::intel::experimental::register_map_key>>::value': The properties conduit and register_map cannot bespecified at the same time.
  202 |   static_assert(detail::hasConduitAndRegisterMap<Props...>::value,
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

2023-10-30 20:46 UTC, dm-vodopyanov approved these changes

2023-10-31 16:46 UTC, tiwaria1 requested changes
Change itself LGTM. Can you check if it is possible to add tests for this in the intel/llvm e2e set? Or other any other intel/llvm set that allows adding negative tests?

2023-11-02 19:23 UTC, yug-intel commented
@tiwaria1 I have added a negative test `annotated_arg_negative.cpp` under `sycl/test/extensions/annotated_arg/`.

2023-11-02 20:31 UTC, tiwaria1 approved these changes

2023-11-02 21:43 UTC, againull commented
@yug-intel Could you please fix formatting issues.

2023-11-03 03:49 UTC, merged