[SYCL][UR] Combined CTS fixes for CL adapter.
intel/llvm pull request #11794
Opened 2023-11-06 16:27 UTC by aarongreig

Pulls in fixes from https://github.com/oneapi-src/unified-runtime/pull/1044

2023-11-10 13:28 UTC, kbenzie requested changes
Not that https://github.com/oneapi-src/unified-runtime/pull/1044 has merged, please pull in the latest sycl branch changes and update the `UNIFIED_RUNTIME_REPO`/`UNIFIED_RUNTIME_TAG` values as suggested. Then make this PR ready to review.

2023-11-10 13:28 UTC, kbenzie commented on sycl/plugins/unified_runtime/CMakeLists.txt
> +  set(UNIFIED_RUNTIME_TAG f65473d9315c1319538f481d7a8c82dd2710c933)
```suggestion
  set(UNIFIED_RUNTIME_REPO "https://github.com/oneapi-src/unified-runtime.git")
  # commit 192e9404392c38ac43d09116d6c97e153c66f46b
  # Merge: 2f44433c f65473d9
  # Author: Kenneth Benzie (Benie) <k.benzie@codeplay.com>
  # Date:   Fri Nov 10 13:25:42 2023 +0000
  #     Merge pull request #1044 from aarongreig/aaron/clCTSFixMegaBranch
  #     [OpenCL] Combined CTS fixes
  set(UNIFIED_RUNTIME_TAG 192e9404392c38ac43d09116d6c97e153c66f46b)
```

2023-11-10 13:53 UTC, kbenzie approved these changes
UR LGTM

2023-11-10 14:47 UTC, martygrant approved these changes

2023-11-13 11:14 UTC, kbenzie commented
@intel/llvm-reviewers-runtime please review, it is intended for the next release.

2023-11-14 09:56 UTC, aarongreig commented on sycl/plugins/unified_runtime/pi2ur.hpp
> +    size_t NumArgs = 0;
It turned out this particular query has always been `size_t` in UR, one of the fixes we're pulling in causes that to be properly validated now so we need to do this bit of translation. We do plan to fix this for the next release cycle https://github.com/oneapi-src/unified-runtime/issues/1038

2023-11-14 16:24 UTC, aelovikov-intel approved these changes

2023-11-14 16:24 UTC, merged