[SYCL][NATIVECPU] Move Native CPU adapter to UR.
intel/llvm pull request #11804
Opened 2023-11-07 15:36 UTC by martygrant

UR PR - https://github.com/oneapi-src/unified-runtime/pull/1047

2023-11-09 18:46 UTC, fabiomestre commented on sycl/plugins/unified_runtime/CMakeLists.txt
> +if ("opencl" IN_LIST SYCL_ENABLE_PLUGINS)
Should be "native_cpu"

2023-11-09 18:46 UTC, fabiomestre commented on sycl/plugins/unified_runtime/ur/adapters/native_cpu/README.md
> +# Cuda adapter
Should be Native CPU adapter

2023-11-10 10:39 UTC, martygrant commented on sycl/plugins/unified_runtime/CMakeLists.txt
> +if ("opencl" IN_LIST SYCL_ENABLE_PLUGINS)
Thanks updated now.

2023-11-10 10:39 UTC, martygrant commented on sycl/plugins/unified_runtime/ur/adapters/native_cpu/README.md
> +# Cuda adapter
Thanks updated now.

2023-11-10 14:12 UTC, PietroGhg approved these changes
Native CPU LGTM, thank you

2023-11-13 09:30 UTC, isaacault approved these changes
`sycl/plugins/unified_runtime/ur/adapters/native_cpu/image.cpp` LGTM

2023-11-14 16:43 UTC, kbenzie approved these changes

2023-11-14 16:49 UTC, kbenzie requested changes

2023-11-14 16:49 UTC, kbenzie commented on sycl/plugins/unified_runtime/CMakeLists.txt
> +  set(UNIFIED_RUNTIME_TAG martin/moveNativeCPUAdapterToUR)
Now that  Please update https://github.com/oneapi-src/unified-runtime/pull/1059 has merged please pull in the latest changes from the sycl branch and update the `UNIFIED_RUNTIME_REPO` and `UNIFIED_RUNTIME_TAG` as follows.

```suggestion
  set(UNIFIED_RUNTIME_REPO "https://github.com/oneapi-src/unified-runtime.git")
  # commit 659d3f469faa99a886fa680a3d6d20449b109578
  # Merge: 192e9404 f94550b4
  # Author: Kenneth Benzie (Benie) <k.benzie@codeplay.com>
  # Date:   Tue Nov 14 16:45:24 2023 +0000
  #     Merge pull request #1059 from martygrant/martin/moveNativeCPUAdapterToUR
  #     [NATIVECPU] Move Native CPU adapter to UR.
  set(UNIFIED_RUNTIME_TAG 659d3f469faa99a886fa680a3d6d20449b109578)
```

2023-11-14 17:20 UTC, kbenzie approved these changes

2023-11-14 21:28 UTC, kbenzie commented
@intel/llvm-gatekeepers this is ready to merge.

2023-11-14 21:31 UTC, merged