[UR] Update UR revision to [CUDA REV]
intel/llvm pull request #11880
Opened 2023-11-14 14:58 UTC by fabiomestre

2023-11-15 10:54 UTC, kbenzie requested changes
Now that https://github.com/oneapi-src/unified-runtime/pull/1077 is merged, please pull in the latest sycl branch changes and update `UNIFIED_RUNTIME_REPO` and `UNIFIED_RUNTIME_TAG` as suggested. Update the title/description and make this PR ready for review.

2023-11-15 10:54 UTC, kbenzie commented on sycl/plugins/unified_runtime/CMakeLists.txt
> +  set(UNIFIED_RUNTIME_TAG d164792b78cb1f6e683dd5e484af9ac7fb061b4e)
```suggestion
  set(UNIFIED_RUNTIME_REPO "https://github.com/oneapi-src/unified-runtime.git")
  # commit 534071e52f84bad1dd7fb210a360414507f3b3ae
  # Merge: 9fc82304 d164792b
  # Author: Kenneth Benzie (Benie) <k.benzie@codeplay.com>
  # Date:   Wed Nov 15 10:51:54 2023 +0000
  #     Merge pull request #1077 from fabiomestre/fabio/combines_fixes_cuda_hip
  #     [CUDA][HIP] Combined CTS Fixes
  set(UNIFIED_RUNTIME_TAG 534071e52f84bad1dd7fb210a360414507f3b3ae)
```

2023-11-15 11:31 UTC, fabiomestre commented on sycl/plugins/unified_runtime/CMakeLists.txt
> +  set(UNIFIED_RUNTIME_TAG d164792b78cb1f6e683dd5e484af9ac7fb061b4e)
Done :+1:

2023-11-15 11:33 UTC, kbenzie approved these changes

2023-11-17 22:29 UTC, kbenzie commented
@intel/llvm-gatekeepers please merge.

2023-11-17 22:42 UTC, merged