[SYCL] add dependent-load flag to exclude CWD from default search path
intel/llvm pull request #12219
Opened 2023-12-20 15:10 UTC by ykhatav

2023-12-21 14:59 UTC, kraszkow requested changes

2023-12-21 14:59 UTC, kraszkow commented on sycl/plugins/level_zero/CMakeLists.txt
> + target_link_options(pi_level_zero PUBLIC /DEPENDENTLOADFLAG:0x800)
I would suggest adding comment what "magic number" 0x800 is (LOAD_LIBRARY_SEARCH_SYSTEM32).

2023-12-22 21:05 UTC, againull approved these changes

2023-12-22 22:11 UTC, kraszkow approved these changes
LGTM

2023-12-22 22:16 UTC, againull commented
@unified-runtime-reviewers Could you please review.

2023-12-26 14:47 UTC, aarongreig requested changes

2023-12-26 14:47 UTC, aarongreig commented on sycl/plugins/level_zero/CMakeLists.txt
> + target_link_options(pi_level_zero PUBLIC /DEPENDENTLOADFLAG:0x800)
this file uses two spaces for indentation
```suggestion
  # 0x800: Search for the DLL only in the System32 folder
  target_link_options(pi_level_zero PUBLIC /DEPENDENTLOADFLAG:0x800)
```

2023-12-29 20:06 UTC, merged