[DOC][SYCL][Graph] need warmup before recording if necessary
intel/llvm pull request #12357
Opened 2024-01-11 07:32 UTC by guoyejun

sometimes, the existing code does some extra work which should not be recorded, and so a warmup is needed for this case.

2024-01-12 02:38 UTC, guoyejun commented
hope to see it soon, it is an important guideline for recording the function calls from libraries in the oneapi package such as onednn, onemkl, etc.

2024-01-12 16:08 UTC, reble requested changes
I agree with @Bensuo by not adding such a guideline to the spec extension. From my perspective, a better place to put interactions with this extension listing workarounds and limitations could be a library documentation.

2024-01-13 13:09 UTC, guoyejun commented
It can be in the library doc at last, but before that, we need a place from sycl side for this guideline.

2024-08-12 10:22 UTC, EwanC commented
A usage guide was created in https://github.com/intel/llvm/pull/14965 and this information added to it, so think this PR can be closed or modified to update the wording in that usage guide if it isn't sufficient.

2024-08-14 09:04 UTC, closed without merging