[SYCL] Add a CUDA compatibilty mode
intel/llvm pull request #12757
Opened 2024-02-19 11:41 UTC by Naghasan

This patch enables CUDA mode at the same time as the SYCL mode. This allows the compiler to define CUDA macros and add implicit defines.

To enable the mode the user adds -fsycl-cuda-compat to the command line. By default this mode is set to off. The flag is only used for the NVPTX backend.

The intent is to help to transition from CUDA to SYCL. Using this mode enable a SYCL application to reuse CUDA functionnalities, especially fast paths that are guarded by __CUDA_ARCH__.

2024-02-19 21:30 UTC, jinz2014 commented
Users may call CUDA kernels in a SYCL program. Is that right ?  Thanks

2024-02-19 21:37 UTC, Naghasan commented
Part of the idea is to allow user to call CUDA device functions from a SYCL kernel. The underlying motivation is actually to have a mode that would support the definition of `__CUDA_ARCH__`.

2024-02-20 01:16 UTC, jinz2014 commented
Okay. Would the compiler allow a SYCL program to mix CUDA and SYCL APIs ?  Some CUDA APIs have no SYCL equivalents.

2025-02-13 03:49 UTC, keryell commented
Adding `[CUDA]` in the git title line?

2025-02-13 22:13 UTC, elizabethandrews commented on clang/lib/Sema/SemaSYCL.cpp
> +  if (((Ty->isFloat128Type() ||
Why is this part of this PR? What happens in tests below if you keep this code as-is?

2025-02-13 22:13 UTC, elizabethandrews commented on clang/test/SemaSYCL/CudaCompat/stub.debug.cpp
> +// RUN: %clang_cc1 %s -fsycl-is-host -aux-triple nvptx64-nvidia-cuda -debug-info-kind=constructor -dwarf-version=5 -fsycl-cuda-compatibility -emit-llvm -O3 -o %t
Can you explain what you are testing here and why you're testing at O3?

2025-02-13 22:13 UTC, elizabethandrews commented on clang/test/SemaSYCL/CudaCompat/delayed-diags.cu
> +// RUN: %clang_cc1 %s -fsycl-is-host -fsycl-cuda-compatibility \
Please add a comment explaining any new test you're adding

2025-02-13 22:13 UTC, elizabethandrews commented on clang/test/SemaSYCL/CudaCompat/delayed-diags.cu
> +// RUN:   -emit-llvm -o - -verify -verify-ignore-unexpected=note
Why `-verify-ignore-unexpected=note`

2025-02-13 22:45 UTC, mdtoguchi commented on clang/include/clang/Driver/Options.td
> +          NegFlag<SetFalse, [], [ClangOption, CLOption, DXCOption, CC1Option], "Disable CUDA compatibility mode.">>;
The additional `DXCOption` driver enabling is not necessary - we don't support that driver.

2025-02-17 13:17 UTC, Naghasan commented on clang/test/SemaSYCL/CudaCompat/delayed-diags.cu
> +// RUN:   -emit-llvm -o - -verify -verify-ignore-unexpected=note
I took the cmd from another and missed this. Removed.

2025-03-04 22:02 UTC, elizabethandrews reviewed
I'm pulling in @premanandrao and @tahonermann into this review because my lack of experience with CUDA makes this a very confusing PR for me and I am not sure if I am the best person for this review.

2025-03-14 23:28 UTC, tahonermann requested changes
Initial incomplete review comments. I'll resume on Monday.

2025-03-17 12:43 UTC, Naghasan commented on clang/include/clang/Sema/SemaCUDA.h
> +  // Note: in SYCL-CUDA compatibility mode: Native, SameSide and HostDevice
Interesting, I haven't looked at nvcc as it is a bit irrelevant though, we have to base our behaviour against what clang cuda does. And it works with clang cuda https://godbolt.org/z/a85dborKh.

Rereading the header, it is only a `__device__` vs `__host__ __device__` issue, yet this is the same problem. I only pushed the testing to include the 3.

Clang provided headers defined `acos` like this https://github.com/intel/llvm/blob/sycl/clang/lib/Headers/__clang_cuda_cmath.h#L241 and my gcc defines its version as `constexpr` so implicitly `__host__ __device__` and the call to `acos` is never ambiguous so they are exploiting the situation (although not exactly as initially mentioned)

2025-03-17 14:16 UTC, Naghasan commented on clang/lib/Driver/ToolChains/Clang.cpp
> +      if (SYCLTriple.isNVPTX() && IsSYCLCUDACompat && !IsSYCLDevice) {
It is confusing indeed. Basically it allows the FE to source type definition, header includes and builtin definitions from 2 different sources host a device. In SYCL, we only host the aux device for the device compilation step to allow host builtins and type def and headers to be available. CUDA uses it also for the host to allow NVPTX builtins to be available during the host compilation step. One of the reason is you can have things like:

```cpp
__device__ void my_bar() {
  __sync_threads();
}
```
`__sync_threads` is only available if you have an NVPTXTargetInfo. You also need to include clang's CUDA headers.

> Is there a restriction that, when targeting NVPTX, other device kinds cannot be targeted?

I don't think so but I don't test it here as it is currently out of scope (follow up).

>  What happens if SYCLTCRange contains multiple NVPTX targets?

That can't happen, the driver creates one TC per target.

> is -aux-triple a positional option that can be specified multiple times?

No there is only one possible.

2025-03-17 19:59 UTC, tahonermann commented on clang/include/clang/Sema/SemaCUDA.h
> +  // Note: in SYCL-CUDA compatibility mode: Native, SameSide and HostDevice
Thanks for the example. I checked the CUDA Programming Guide to see if it says anything about overloading of the `__host__` and `__device__` specifiers and I didn't find anything (which isn't surprising; there is a reason it is called a programming guide and not a language specification). Clang's behavior makes sense and it is certainly more convenient to rely on overloading than to have to sprinkle `#ifdef __CUDA_ARCH__` anywhere different implementations would otherwise be desired. I think this comment can be resolved.

2025-03-17 20:47 UTC, tahonermann commented on clang/lib/Driver/ToolChains/Clang.cpp
> +      if (SYCLTriple.isNVPTX() && IsSYCLCUDACompat && !IsSYCLDevice) {
> >   What happens if SYCLTCRange contains multiple NVPTX targets?

> That can't happen, the driver creates one TC per target.

Hmm, that is odd then that `getOffloadToolChains()` returns a range of tool chains, that they are all enumerated here, and that a `-aux-triple` option will also be added if there is an FPGA target. Since host compilation is only performed once, how would one perform a build that supports NVPTX, SPIR-V and AMD devices? Is separate device compilation currently required for that?

2025-03-17 21:25 UTC, tahonermann reviewed
Still working my way through...

2025-03-17 21:25 UTC, tahonermann commented on clang/lib/Basic/Targets/NVPTX.cpp
> +    if (!Opts.SYCLIsDevice || Opts.SYCLCUDACompat)
`!Opts.SYCLIsDevice` implies host compilation (or non-SYCL compilation) to me. `__CUDA_ARCH__` shouldn't be defined for host compilation; at least not when compiling for CUDA. I wouldn't expect SYCL-CUDA to be different in this respect; the host code should be independent of any particular CUDA device.

2025-03-17 21:25 UTC, tahonermann commented on clang/lib/CodeGen/CodeGenFunction.cpp
> +  if (getLangOpts().CUDA && !getLangOpts().CUDAIsDevice &&
Would it suffice to check for just `getLangOpts().SYCLCUDACompat` instead of both `getLangOpts().CUDA` and `!getLangOpts().CUDAIsDevice` (since there is already a check for `getLangOpts().SYCLIsHost`)?

2025-03-17 21:25 UTC, tahonermann commented on clang/lib/Driver/ToolChains/Clang.cpp
> +static bool hasSYCLCudaCompatFlag(const ArgList &Args) {
Pedantic naming suggestion comment that you should feel free to ignore.
```suggestion
static bool isSYCLCudaCompatEnabled(const ArgList &Args) {
```

2025-03-17 21:25 UTC, tahonermann commented on clang/lib/Driver/ToolChains/Clang.cpp
> +                        options::OPT_fno_sycl_cuda_compat);
Use of `addOptInFlag()` is a little odd here given that `IsSYCLCUDACompat` is already known to be true.

2025-03-17 21:25 UTC, tahonermann commented on clang/lib/Frontend/CompilerInvocation.cpp
> +      Args.hasArg(OPT_fsycl_cuda_compat, OPT_fno_sycl_cuda_compat, false);
Use of `hasSYCLCudaCompatFlag()` would be preferred here. That means exposing it out of just `Clang.cpp` though.

2025-03-17 22:06 UTC, Naghasan commented on clang/lib/Driver/ToolChains/Clang.cpp
> +      if (SYCLTriple.isNVPTX() && IsSYCLCUDACompat && !IsSYCLDevice) {
> Hmm, that is odd then that getOffloadToolChains() returns a range of tool chains

You basically have 1 TC per target triple. CUDA assumes nvptx so uses the variant returning 1 but SYCL supports many, so this can happen.

> and that a -aux-triple option will also be added if there is an FPGA target

no it won't, that's guarded by `SYCLTriple.isNVPTX()`

> Since host compilation is only performed once, how would one perform a build that supports NVPTX, SPIR-V and AMD devices?

As i mentioned before, currently out of scope and that's for a future patch. Although the scope to include that aux triple on the host is to handle the cuda code mentioned above (device side that doesn't get emitted) which is specific to CUDA / nvptx. So, in that case, the aux-triple will be nvptx regardless. Note the aux-triple for host compilation isn't as invasive as it is for device compilation.

2025-03-17 22:56 UTC, Naghasan commented on clang/lib/Basic/Targets/NVPTX.cpp
> +    if (!Opts.SYCLIsDevice || Opts.SYCLCUDACompat)
We are inside this scope `if (Opts.CUDAIsDevice || Opts.OpenMPIsTargetDevice || Opts.SYCLIsDevice || !HostTarget) {`

so `!Opts.SYCLIsDevice` means a non SYCL device compilation here.

2025-03-17 22:56 UTC, Naghasan commented on clang/lib/Driver/ToolChains/Clang.cpp
> +                        options::OPT_fno_sycl_cuda_compat);
true, but I haven't find a simpler function to render the arg using `options::OPT_fsycl_cuda_compat`. The alternative is `CmdArgs .push_back("-fsycl-cuda-compat")`. Quite common but quite dislike this (just like for the default args). Happy to change though.

2025-03-17 22:56 UTC, Naghasan commented on clang/lib/Frontend/CompilerInvocation.cpp
> +      Args.hasArg(OPT_fsycl_cuda_compat, OPT_fno_sycl_cuda_compat, false);
yes and sharing between the driver and frontend module.

2025-03-17 22:56 UTC, Naghasan commented on clang/lib/CodeGen/CodeGenFunction.cpp
> +  if (getLangOpts().CUDA && !getLangOpts().CUDAIsDevice &&
We also want the `!CUDAIsDevice` check because of Paolo's use case (see linked PR).

2025-03-18 03:17 UTC, tahonermann commented on clang/lib/Driver/ToolChains/Clang.cpp
> +                        options::OPT_fno_sycl_cuda_compat);
Ok, yeah, I looked and I don't see a better way to handle this either. Ok, nothing to see here.

2025-03-18 03:28 UTC, tahonermann commented on clang/lib/Driver/ToolChains/Clang.cpp
> +      if (SYCLTriple.isNVPTX() && IsSYCLCUDACompat && !IsSYCLDevice) {
Ah, I missed the `break` statements present for both the `if (SYCLTriple.isNVPTX() ...)` and `if (SYCLTriple.getSubArch() == llvm::Triple::SPIRSubArch_fpga)` conditions in the loop. The loop will effectively select the first matching tool chain kind it finds. I hope the FPGA folks don't mind getting preempted by an NVPTX target :)

> Note the aux-triple for host compilation isn't as invasive as it is for device compilation.

Yeah, but still fundamentally wrong. But pre-existing wrong, so not your problem to fix.

Thanks for guiding me through this.

2025-03-18 04:33 UTC, tahonermann reviewed
Completed code review. I haven't looked at the last few tests that exercise overload resolution. I'll look at those early tomorrow.

2025-03-18 04:33 UTC, tahonermann commented on clang/lib/Sema/SemaCUDA.cpp
> +// | hd | hd |    SS    |     HD     |     SS(s2)| (b) |
I can't find a legend for what the parenthesized values mean in the various columns and I'm not able to intuit their meaning.

2025-03-18 04:33 UTC, tahonermann commented on clang/lib/Sema/SemaCUDA.cpp
> +// They should be understood as 1st, 2nd or 3rd choice.
This comment could use some more elaboration. There are five values listed, but only three are ranked, presumably because `WS` and `--` are invalid scenarios. I'm also not sure how to apply the ranking in the table below. I think I understand the intent from discussion elsewhere, but I'm having a hard time seeing it in the table.

2025-03-18 04:33 UTC, tahonermann commented on clang/lib/Sema/SemaCUDA.cpp
> +// | hd | hd |    SS    |     HD     |     SS(s2)| (b) |
I can't find a legend for what the parenthesized values mean in the various columns and I'm not able to intuit their meaning.

2025-03-18 04:33 UTC, tahonermann commented on clang/lib/Sema/SemaDecl.cpp
> +  if (getLangOpts().CUDA && !getLangOpts().SYCLCUDACompat)
The commend states, "In SYCL-CUDA compat mode" but the if statement condition checks for `!getLangOpts().SYCLCUDACompat`.

2025-03-18 04:33 UTC, tahonermann commented on clang/test/SemaSYCL/CudaCompat/delayed-diags.cu
> +// and triggers SYCL's delayed diagnostics.
Grammar seems wrong; "this leaves the diagnostic logic for CUDA it is processing the host side".

2025-03-18 04:33 UTC, tahonermann commented on clang/test/SemaSYCL/CudaCompat/delayed-diags.cu
> +}
Why would a diagnostic be required for a non-const static local variable? The function isn't explicitly annotated as host, device, or both (I thus expect it to be implicitly host-only), nor is it used within the TU.

2025-03-18 15:44 UTC, tahonermann commented on clang/test/SemaSYCL/CudaCompat/delayed-diags.cu
> +}
Right, but why would there ever be an expectation of a diagnostic here? A non-const static local variable is not an error in any configuration that I'm aware of.

2025-03-18 17:24 UTC, tahonermann commented on clang/lib/CodeGen/CodeGenFunction.cpp
> +  if (getLangOpts().CUDA && !getLangOpts().CUDAIsDevice &&
Per chat discussion, I find this use of `SYCLIsHost` really confusing and hard to reason about. However, I acknowledge that this use is pre-existing and that this logic was just moved from a few lines above. I think it would be helpful to clarify the comment below (currently at line 1880) with something like the following would help.
```
// SYCL host compilation with CUDA compatibility enabled requires
// the creation of a host stub function for functions declared with
// the __device__ specifier but without the __host__ specifier.
```

2025-03-18 17:33 UTC, tahonermann commented on clang/lib/Driver/ToolChains/Clang.cpp
> +      CmdArgs.push_back("-fdeclspec");
There is currently a FIXME in `clang/include/clang/Driver/Options.td` regarding the use of `declspec` in `clang/lib/Headers/__clang_cuda_builtin_vars.h`. Perhaps elevate this comment to a FIXME as well since this is effectively a workaround.

2025-03-18 18:18 UTC, tahonermann commented on clang/test/SemaSYCL/CudaCompat/overloads.h
> +} // namespace bar
It doesn't look like any of the tests exercise the overloads in the `bar` namespace and `bar` isn't an inline namespace. Is this just intended to ensure all three overloads can exist? The tests don't seem to be exercising ranking of a `__device__ __host__` overload within an overload set.

2025-03-18 18:19 UTC, tahonermann reviewed
I've completed review. Just waiting to resolve open comments before approving.

2025-03-18 21:55 UTC, Naghasan commented on clang/lib/Driver/ToolChains/Clang.cpp
> +      CmdArgs.push_back("-fdeclspec");
changed into a  FIXME

2025-03-18 21:55 UTC, Naghasan commented on clang/test/SemaSYCL/CudaCompat/overloads.h
> +} // namespace bar
no, just a facepalm moment... I wrote the header first and the check for this last....

Fixed the test to call `bar::overload()`

2025-03-18 22:05 UTC, Naghasan commented on clang/test/SemaSYCL/CudaCompat/delayed-diags.cu
> +}
> A non-const static local variable is not an error in any configuration that I'm aware of.

It is in device code (see last bullet point in https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#sec:language.restrictions.kernels). During the processing of the file, this decl triggers a delayed diagnostic and this is asserting it is never actually raised as `get` is never emitted during the device compilation.

2025-03-18 22:26 UTC, Naghasan commented on clang/lib/CodeGen/CodeGenFunction.cpp
> +  if (getLangOpts().CUDA && !getLangOpts().CUDAIsDevice &&
Added comment

2025-03-18 22:26 UTC, Naghasan commented on clang/lib/Frontend/InitPreprocessor.cpp
> +  if (LangOpts.CUDA || LangOpts.SYCLCUDACompat) {
It is, removed, thanks

2025-03-18 22:26 UTC, Naghasan commented on clang/lib/Sema/SemaDecl.cpp
> +  if (getLangOpts().CUDA && !getLangOpts().SYCLCUDACompat)
Clarify the comment to be less confusing

2025-03-18 22:42 UTC, Naghasan commented on clang/lib/CodeGen/CodeGenFunction.cpp
> +  if (getLangOpts().CUDA && !getLangOpts().CUDAIsDevice &&
Created https://github.com/intel/llvm/issues/17519 for the `SYCLIsHost` issue

2025-03-18 22:57 UTC, Naghasan commented on clang/lib/CodeGen/CodeGenFunction.cpp
> +  if (getLangOpts().CUDA && !getLangOpts().CUDAIsDevice &&
Create https://github.com/intel/llvm/issues/17520 to unify better with the CUDA TU support.

2025-03-18 23:04 UTC, Naghasan commented on clang/lib/Sema/SemaCUDA.cpp
>  // | F  | T  | Ph - Sh  |  Pd - Sh   |  Ph - Sd  |  H  |
will address with https://github.com/intel/llvm/issues/17520

2025-03-19 02:28 UTC, tahonermann commented on clang/test/SemaSYCL/CudaCompat/delayed-diags.cu
> +}
Thank you, I wasn't aware of that requirement (or had forgotten it). This makes perfect sense now.

2025-03-19 02:37 UTC, tahonermann approved these changes
Looks good. Thank you for sticking with me through all the comments and helping me to understand the changes!

2025-03-19 14:09 UTC, mdtoguchi approved these changes
LGTM

2025-03-19 16:37 UTC, elizabethandrews approved these changes

2025-03-20 09:12 UTC, Naghasan commented
@intel/llvm-gatekeepers this is ready to be merged, Jenkins jobs failure is unrelated to the patch (it can't create a node ...)

2025-03-20 09:14 UTC, merged