Testing add validation tests to getInfo tests
intel/llvm pull request #12782
Opened 2024-02-21 14:41 UTC by omarahmed1111

Testing PR for [UR PR](https://github.com/oneapi-src/unified-runtime/pull/1346)

2024-03-01 11:04 UTC, omarahmed1111 commented on sycl/test-e2e/KernelFusion/cooperative_kernel.cpp
> -
This test is not failing anymore after changing hip program info returned for program device to return context device and not the binary associated device.

2024-03-01 11:50 UTC, victor-eds requested changes
Changes LGTM. Can we have an explanation of why the test is passing in the commit message?

2024-03-01 12:33 UTC, omarahmed1111 commented
> Changes LGTM. Can we have an explanation of why the test is passing in the commit message?

Done. Thanks for pointing that!

2024-03-01 13:11 UTC, victor-eds commented
Correction:

>After correcting hip program info returned for program device to return context device rather than the binary associated device that have fixed the **kernel fusion** cooperative kernels e2e test.

2024-04-29 09:42 UTC, kbenzie reviewed
The UR PR has merged, please update the UR repo/tag varaibles as suggested.

2024-04-29 09:42 UTC, kbenzie commented on sycl/plugins/unified_runtime/CMakeLists.txt
> +  set(UNIFIED_RUNTIME_TAG cbd581fbe4182ac443aa17edf2214cd05369a110)
```suggestion
  set(UNIFIED_RUNTIME_REPO "https://github.com/oneapi-src/unified-runtime.git")
  # commit a6cdcf4591779a925c5f017a19c26ea171797edf
  # Merge: 54829f00 cbd581fb
  # Author: Kenneth Benzie (Benie) <k.benzie@codeplay.com>
  # Date:   Mon Apr 29 10:39:11 2024 +0100
  #     Merge pull request #1346 from omarahmed1111/ensure-getinfo-cts-tests-report-same-dependency-creation-object
  #     Add output validation checks for getInfo tests and a small USM spec fix
  set(UNIFIED_RUNTIME_TAG cbd581fbe4182ac443aa17edf2214cd05369a110)
```

2024-04-30 09:04 UTC, kbenzie commented
@intel/llvm-gatekeepers please merge

2024-04-30 10:04 UTC, merged