[CLC][AMDGPU] Refactor fence helper to process order semantic explicitly
intel/llvm pull request #12872
Opened 2024-02-29 16:42 UTC by GeorgeWeb

2024-03-05 17:23 UTC, JackAKirk approved these changes
LGTM

2024-03-28 10:54 UTC, GeorgeWeb commented
The linked unified-runtime changes https://github.com/oneapi-src/unified-runtime/pull/1414 enable support for all the memory order semantics.

2024-06-13 09:24 UTC, kbenzie approved these changes

2024-06-13 13:15 UTC, kbenzie commented
@intel/llvm-gatekeepers please merge

2024-06-13 13:16 UTC, kbenzie requested changes

2024-06-13 13:16 UTC, kbenzie commented on sycl/plugins/unified_runtime/CMakeLists.txt
> +    https://github.com/GeorgeWeb/unified-runtime.git
```suggestion
    ${UNIFIED_RUNTIME_REPO}
```

2024-06-13 13:31 UTC, kbenzie requested changes

2024-06-13 13:31 UTC, kbenzie commented on sycl/plugins/unified_runtime/CMakeLists.txt
> +    2c4303c25b026f7edb215accdccb1bc5ae2e237b
```suggestion
    # commit 0e32bb59e0846cbe8153c294da6d8f1cfa88075b
    # Merge: 2c4303c2 08b19b22
    # Author: Kenneth Benzie (Benie) <k.benzie@codeplay.com>
    # Date:   Thu Jun 13 14:15:42 2024 +0100
    #     Merge pull request #1415 from GeorgeWeb/georgi/hip-atomic-memory-caps
    #     [HIP] Enable more ordering and scope capabilities for atomic memory ops
    0e32bb59e0846cbe8153c294da6d8f1cfa88075b
```

2024-06-13 13:50 UTC, kbenzie approved these changes

2024-06-13 15:58 UTC, merged