[SYCL] Pass -O0 by default when -g is set
intel/llvm pull request #12922
Opened 2024-03-06 13:59 UTC by MrSidims

When -g is passed and no optimization flag was specified explicitly - the default opt level should be O0

2024-03-06 15:13 UTC, bader commented
> When -g is passed and no optimization flag was specified explicitly - the default opt level should be O0

I don't think `-g` should change the optimization level. Why do you think it "should be O0"?

2024-03-06 17:17 UTC, MrSidims commented
> > When -g is passed and no optimization flag was specified explicitly - the default opt level should be O0
> 
> I don't think `-g` should change the optimization level. Why do you think it "should be O0"?

@bader As a user I would expect certain level of debuggability when you pass -g, but you are not getting it as O2 is set by default. Also as a user I would expect that CMAKE_BUILD_TYPE=Debug is sufficient to work with debugger. Please, host compiler will pass O0 in this case, resulting in a mismatch in opt level.

Another point (it's not related to intel/llvm) when you try oneAPI compiler with -g and without opt level set you would see a warning:
"icpx: remark: Note that use of '-g' without any optimization-level option will turn off most compiler optimizations similar to use of '-O0'; use '-Rno-debug-disables-optimization' to disable this remark [-Rdebug-disables-optimization]"
where in reality O2 will be still passed (it's not an advocate for this very patch, as for now it's icpx warning bug, but still it's a reason to open a discussion).

2024-03-06 17:28 UTC, bader requested changes
> > > When -g is passed and no optimization flag was specified explicitly - the default opt level should be O0
> > 
> > I don't think `-g` should change the optimization level. Why do you think it "should be O0"?
> 
> @bader As a user I would expect certain level of debuggability when you pass -g, but you are not getting it as O2 is set by default. 

@MrSidims, the fix for this problem is adjusting user expectation about the level of debuggability with today's default optimization level O2. I'm strongly against modifying default optimization level by adding `-g` flag.

> Also as a user I would expect that CMAKE_BUILD_TYPE=Debug is sufficient to work with debugger. Please note, host compiler will pass O0 in this case, resulting in a mismatch in opt level.

I don't follow you here. How does CMake get into the picture here?

> Another point (it's not related to intel/llvm) when you try oneAPI compiler with -g and without opt level set you would see a warning:
> "icpx: remark: Note that use of '-g' without any optimization-level option will turn off most compiler optimizations similar to use of '-O0'; use '-Rno-debug-disables-optimization' to disable this remark [-Rdebug-disables-optimization]"
> where in reality O2 will be still passed (it's not an advocate for this very patch, as for now it's icpx warning bug, but still it's a reason to open a discussion).

Please, file a bug on icpx. If icpx behavior will change as said in the warning, feel free to open a discussion about aligning clang's driver behavior with icpx, but I don't think any other compiler changes default optimization level if user requests adding debug information.

2024-07-31 21:09 UTC, bader commented
@MrSidims, ping. What do you plan to do with this pull request?

2025-02-27 02:00 UTC, closed without merging