[SYCL][COMPAT] Extended device_info properties.
intel/llvm pull request #13050
Opened 2024-03-18 09:08 UTC by Alcpz

- Adds multiple properties to syclcompat's device_info class.
- Usage of `sycl::id` deprecated in favour of `sycl::range`.
- Refactored queue creation, implementation moved to a private method. 
- Device name truncated if it's name exceeds the maximum buffer size (256 by default).

Minor:
- Updated format of device tests to match the current test style used for other headers.

2024-03-25 13:54 UTC, AidanBeltonS requested changes
Some changes/clarifications needed

2024-03-25 13:54 UTC, AidanBeltonS commented on sycl/doc/syclcompat/README.md
> +  void get_memory_info(size_t &free_memory, size_t &total_memory);
Should this function also be `const` or does this alter the memory within the `device_ext` class?

2024-03-25 13:54 UTC, AidanBeltonS commented on sycl/include/syclcompat/device.hpp
> +    _saved_queue = _default_queue =
Not sure I really like this syntax. Feel free to keep if you feel its fine, but I would consider this unnecessarily difficult to read

2024-03-25 13:54 UTC, AidanBeltonS commented on sycl/include/syclcompat/device.hpp
> +  void destroy_queue(sycl::queue *&queue) {
Whats the motivation for this change from queue_ptr -> sycl:queue *?
I think it is a bit less readable, even if it is the same underneath.

2024-03-25 13:54 UTC, AidanBeltonS commented on sycl/include/syclcompat/device.hpp
> +    std::lock_guard<std::recursive_mutex> lock(m_mutex);
I think changing the mutex type is unnecessary.

2024-04-11 12:19 UTC, AidanBeltonS approved these changes
LGTM

2024-04-11 13:16 UTC, Alcpz commented
@intel/llvm-gatekeepers PR is ready to merge. Thanks!

2024-04-11 13:17 UTC, merged