[CI] Enable post commit for sycl-web pushes
intel/llvm pull request #13138
Opened 2024-03-23 03:10 UTC by jsji

In we may get regressions almost every pulldown, we currently only
expose them when we create the pulldown PR. The pulldown may be delayed
if we get multiple failures.
This is to enable post commit CI to pushes to sycl-web so that we can
know the regressions ealier and may fix the regressions earlier to avoid
delay to pulldown.

2024-03-23 03:59 UTC, aelovikov-intel requested changes
I'm afraid we don't have HW resources in CI for that.

2024-03-23 14:14 UTC, jsji commented
> I'm afraid we don't have HW resources in CI for that.

I think this will just add 2-3 post commits run per day. 

># git ld3 --merges --since 2024-01-01|grep 'Merge.*sycl-web'|wc
>     131    1696   11014
> # git ld3 --merges --since 2024-02-01|grep 'Merge.*sycl-web'|wc
>      86    1113    7215
> # git ld3 --merges --since 2024-03-01|grep 'Merge.*sycl-web'|wc
>      53     692    4446

workdays since 2024-01-01 57
workdays since 2024-02-01 36
workdays since 2024-03-01 16

131/57 = 2.3
86/36 = 2.4
53/16 = 3.3

2024-03-23 15:01 UTC, jsji commented
![image](https://github.com/intel/llvm/assets/1674522/5b155be0-4ad9-44b3-93a2-e804b3e3899b)

We have ~12  post-commit CI runs per day, the normal duration is 1 hour, worst 4 hours, average 1.6 hours.
I think we should be able to afford 3 more CI runs.
There are days that we encounter problems and get around 4 hours per run, but I would consider that is abnormal, in that case, we can definitely cancel sycl-web runs.

2024-03-25 15:07 UTC, aelovikov-intel commented
1) We are already latency bound during work hours
2) Post-commit is second heaviest workflow
3) Post-commit (build in particular) will be longer than normal for this task, because build cache wouldn't be as useful when generic LLVM/clang are being modified
4) It will also throttle the cache and make a subsequent regular task longer.

I'm still opposed to this PR. Please work with @stdale-intel if you disagree.

2024-03-25 15:23 UTC, jsji commented
Thanks @aelovikov-intel .  I will abandon this PR them, we can revisit this if we want to fix the slow pulldown issue (if it become an issue to the team later).

2024-03-25 15:24 UTC, closed without merging