[SYCL][NATIVECPU] Threadpool implementation for Native CPU
intel/llvm pull request #13176
Opened 2024-03-27 11:19 UTC by PietroGhg

Testing PR for https://github.com/oneapi-src/unified-runtime/pull/1478.

2024-04-02 03:51 UTC, uwedolinsky approved these changes

2024-04-11 10:41 UTC, kbenzie requested changes
Please update the UR repo/tag as suggested.

2024-04-11 10:41 UTC, kbenzie commented on sycl/plugins/unified_runtime/CMakeLists.txt
> +    pietro/vecz_threadpool
```suggestion
    ${UNIFIED_RUNTIME_REPO}
    # commit 38e9478b8a7a01fcf37f55b50c735ca1de29c76d
    # Merge: b582fb80 c594cdc0
    # Author: Kenneth Benzie (Benie) <k.benzie@codeplay.com>
    # Date:   Thu Apr 11 11:39:02 2024 +0100
    #     Merge pull request #1478 from PietroGhg/pietro/vecz_threadpool
    #     [NATIVECPU] Initial threadpool implementation for Native CPU
    38e9478b8a7a01fcf37f55b50c735ca1de29c76d
```

2024-04-11 10:48 UTC, kbenzie approved these changes

2024-04-11 13:25 UTC, PietroGhg commented
Hi @intel/llvm-gatekeepers, this looks ready to be merged, thank you

2024-04-11 13:30 UTC, merged