[SYCL] ABI-neutralize device:: and platform::has_extension
intel/llvm pull request #13212
Opened 2024-03-29 21:33 UTC by bso-intel

By passing a native char *, we can be ABI-neutral.

2024-04-26 16:32 UTC, bso-intel commented
@sergey-semenov 
friendly ping

2024-04-30 16:26 UTC, bso-intel commented
@sergey-semenov 
ping

2024-05-02 11:02 UTC, sergey-semenov approved these changes

2024-07-11 00:06 UTC, bso-intel commented
@intel/llvm-gatekeepers 
Please merge.

2024-07-11 04:42 UTC, steffenlarsen requested changes

2024-07-16 16:11 UTC, bso-intel commented on sycl/include/sycl/device.hpp
> +  bool has_extension(detail::string_view extension_name) const;
Done. Thanks

2024-07-16 16:11 UTC, bso-intel commented on sycl/include/sycl/platform.hpp
> +  bool has_extension(detail::string_view ExtensionName) const;
Done. Thanks

2024-07-17 10:56 UTC, steffenlarsen approved these changes

2024-07-17 18:23 UTC, bso-intel commented
@intel/llvm-gatekeepers 
Please merge.

2024-07-17 19:26 UTC, merged