Added licence header to Joint Matrix tests
intel/llvm pull request #13726
Opened 2024-05-09 14:50 UTC by artemrad

2024-05-09 16:09 UTC, YuriPlyakhin commented on sycl/test-e2e/Matrix/element_wise_all_ops_half_impl.hpp
> +//===--------------------- DPC++ joint_matrix------------------------------===//
please, add file names, see for example here: https://github.com/intel/llvm/blob/4b9819f0b6bf50da03ddc9987918c8d6e09ee757/sycl/test-e2e/Matrix/element_wise_abc_impl.hpp#L1

2024-05-09 16:11 UTC, YuriPlyakhin requested changes
need to make the file headers consistent with the coding standard https://llvm.org/docs/CodingStandards.html#file-headers

2024-05-09 19:27 UTC, YuriPlyakhin commented
Please, resolve formatting problem. thanks.

2024-05-09 20:10 UTC, YuriPlyakhin approved these changes
LGTM.
Please, add [NFC] tag to the title of your PR.

2024-05-10 14:06 UTC, artemrad commented
@intel/llvm-gatekeepers the PR is ready.

2024-05-10 14:11 UTC, merged