[E2E] Fix not enough input provided for private_alloca tests
intel/llvm pull request #13922
Opened 2024-05-27 06:52 UTC by yingcong-wu

For private_alloca tests, every `test()` would require an input number. However, related tests do not provide enough input. This will lead to the undetermined result. This patch adds enough input number to the test, and add a assert to make sure all the read is successful.

2024-05-28 10:50 UTC, victor-eds commented on sycl/test-e2e/PrivateAlloca/ValidUsage/private_alloca_bool_size.cpp
> +// RUN: echo 1 1  | %{run} %t.out
In which cases is this needed? Aren't we reading a single number from stdin? Same for other tests.

2024-05-28 14:15 UTC, victor-eds approved these changes

2024-05-28 15:12 UTC, victor-eds requested changes
Will be replaced by a different PR

2024-05-29 00:43 UTC, yingcong-wu commented
Sure, I will close this PR.

2024-05-29 00:43 UTC, closed without merging