[SYCL][COMPAT] Add device_count and testing
intel/llvm pull request #14013
Opened 2024-06-03 13:10 UTC by AidanBeltonS

This PR adds the syclcompat free function `device_count`.
It provides testing for this new function and for `get_device_id()`

2024-06-03 13:21 UTC, Alcpz reviewed
Can you update the documentation as well for `syclcompat::device_count`?
It's not part of your PR, but it seems I missed adding `syclcompat::get_device_id` (:804 above your new function, sorry about that!). Mind adding that as well?

2024-06-03 14:21 UTC, AidanBeltonS commented
> Can you update the documentation as well for `syclcompat::device_count`? It's not part of your PR, but it seems I missed adding `syclcompat::get_device_id` (:804 above your new function, sorry about that!). Mind adding that as well?
> 
> Other than that, LGTM

Done

2024-06-03 14:21 UTC, Alcpz approved these changes

2024-06-03 16:53 UTC, OuadiElfarouki approved these changes
LGTM

2024-06-05 12:03 UTC, joeatodd requested changes
This has already been reviewed but this merge conflict resolution needs fixed. Otherwise LGTM!

2024-06-05 12:03 UTC, joeatodd commented on sycl/test-e2e/syclcompat/device/device.cpp
> +<<<<<<< HEAD
woops!

2024-06-06 09:54 UTC, joeatodd commented on sycl/test-e2e/syclcompat/device/device.cpp
> +<<<<<<< HEAD
```suggestion
```

2024-06-17 07:51 UTC, joeatodd commented
@intel/llvm-gatekeepers this is ready to merge :pray:

2024-06-19 08:38 UTC, joeatodd commented
@intel/llvm-gatekeepers this is ready to merge :pray:

2024-06-19 08:43 UTC, sommerlukas commented
@joeatodd We can't merge this as is, because the author information is not correct: 
>  This commit will be authored by 87009434+AidanBeltonS@users.noreply.github.com 

@AidanBeltonS would need to update their Github profile settings to put their actual mail address on PR commits.

2024-06-19 09:01 UTC, merged