[SYCL][COMPAT] Add math extend_vcompare[2/4] to SYCLCompat
intel/llvm pull request #14079
Opened 2024-06-06 13:18 UTC by OuadiElfarouki

This PR adds math `extend_vcompare[2/4] `operators (4 in total) along with unit-tests for signed and unsigned int32 cases.
*Some changes overlap with the previous `extend_v*4`  #14078 and `extend_v*2` #13953 and thus should be reviewed/merged first.

2024-06-06 13:45 UTC, Alcpz requested changes
Very minor stuff in the docs, otherwise LGTM, The review assumes that `extend_vbinary2` and `extend_vbinary4` are gonna be reviewed in their respective PRs.

2024-06-06 13:45 UTC, Alcpz commented on sycl/doc/syclcompat/README.md
> +
New functions missing in README

2024-06-06 13:45 UTC, Alcpz commented on sycl/include/syclcompat/math.hpp
> +/// specified comparison \p cmp .
```suggestion
/// specified comparison \p cmp .
///
```

2024-06-06 13:45 UTC, Alcpz commented on sycl/include/syclcompat/math.hpp
> +/// specified comparison \p cmp .
```suggestion
/// specified comparison \p cmp .
///
```

2024-06-06 13:45 UTC, Alcpz commented on sycl/test-e2e/syclcompat/math/math_extend_v.cpp
> +// --------------===//
NIT: adjust to avoid splitting the comment

2024-06-07 10:26 UTC, Alcpz approved these changes

2024-06-13 05:35 UTC, yihanwg approved these changes
LGTM

2024-06-13 13:14 UTC, OuadiElfarouki commented
Due to the timeout of the `math_extend_v` tests causing the CI to fail, I just broke it down to 2 separate test files (one for each vectorization size).

2024-06-13 18:35 UTC, OuadiElfarouki commented
@intel/llvm-gatekeepers PR should be ready! Thanks.

2024-06-14 06:07 UTC, merged