[New offload driver][Device lib] Add SYCL device library files for all targets
intel/llvm pull request #14102
Opened 2024-06-09 01:08 UTC by asudarsa

2024-06-09 01:10 UTC, asudarsa commented on clang/lib/Driver/ToolChains/Clang.cpp
> -    if (TargetTriple.isSPIR())
We should not pass target triple to linker wrapper. This information is available inside the device images.

2024-06-10 19:03 UTC, mdtoguchi approved these changes

2024-06-10 19:03 UTC, mdtoguchi commented on clang/lib/Driver/ToolChains/Clang.cpp
> +        bool IsSpirvAOT = TargetTriple.isSPIRAOT();
nit - I know this was in the old code - but it is odd to use `bool` and `auto` next to each other when they are basically the same usage.

2024-06-11 03:05 UTC, asudarsa commented
@intel/llvm-gatekeepers Can you please merge? This is ready for merging.

Thanks

2024-06-11 06:15 UTC, steffenlarsen requested changes
Driver/sycl-offload-new-driver.c is failing in post-commit after https://github.com/intel/llvm/pull/14091. I am blocking this PR until the patch has either been reverted or the test failure has been addressed.

2024-06-11 14:49 UTC, steffenlarsen approved these changes
Revert was merged. Retracting my blocking comment.

2024-06-11 19:17 UTC, asudarsa commented
@intel/llvm-gatekeepers 
This is ready to be merged. Thanks

2024-06-11 22:24 UTC, merged