[SYCL][Bindless] Fix OpaqueFD's scope in piextImportExternalMemory
intel/llvm pull request #14266
Opened 2024-06-24 03:22 UTC by wenju-he

InteropMemDesc.pNext could be &OpaqueFD, so scope of OpaqueFD should be the same as of InteropMemDesc.

2024-06-24 08:45 UTC, isaacault requested changes
This LGTM but for completeness could you please: 

1. Apply the same change to the below `Win32Handle`
2. Apply both these changes to the duplicated code block in `piextImportExternalSemaphore`

2024-06-24 09:16 UTC, wenju-he commented
> This LGTM but for completeness could you please:
> 
> 1. Apply the same change to the below `Win32Handle`
> 2. Apply both these changes to the duplicated code block in `piextImportExternalSemaphore`

done. Is it right opque fd isn't supported on windows? If so, we can define it on linux and define Win32Handle on windows, so that we don't need to define both of them.

2024-06-24 10:54 UTC, isaacault commented
> done. Is it right opque fd isn't supported on windows? If so, we can define it on linux and define Win32Handle on windows, so that we don't need to define both of them.

Yes that's correct. I agree, we should define them only on their respective OS.

2024-06-25 03:54 UTC, wenju-he commented
> Yes that's correct. I agree, we should define them only on their respective OS.

done. @isaacault Could you please review again?

2024-06-25 10:07 UTC, isaacault approved these changes
Thanks for all this. LGTM!

2024-06-25 10:13 UTC, aarongreig approved these changes

2024-06-25 10:20 UTC, przemektmalon approved these changes

2024-06-25 11:21 UTC, DBDuncan approved these changes

2024-06-26 01:00 UTC, wenju-he commented
@intel/llvm-gatekeepers please merge, thank you.

2024-06-26 06:23 UTC, merged