[SYCL] Renaming fixed_size_group to chunk
intel/llvm pull request #15721
Opened 2024-10-16 13:46 UTC by AndreiZibrov

First part of changes in order of https://github.com/intel/llvm/pull/14604:
fixed_size_group -> chunk

2024-10-16 14:50 UTC, AlexeySachkov requested changes

2024-10-16 14:50 UTC, AlexeySachkov commented on sycl/include/sycl/ext/oneapi/experimental/chunk.hpp
> +get_chunk(Group group);
[`sycl_ext_oneapi_non_uniform_groups`](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/experimental/sycl_ext_oneapi_non_uniform_groups.asciidoc) does not define `get_chunk`, I suppose you meant `chunked_partition`

2024-10-16 14:50 UTC, AlexeySachkov commented on sycl/include/sycl/ext/oneapi/experimental/chunk.hpp
> +template <size_t PartitionSize, typename ParentGroup> class chunk {
We should also leave a `TODO` comment to implement `operator fragment<ParentGroup>() const;` once `fragment` is ready

2024-10-16 14:50 UTC, AlexeySachkov commented on sycl/test-e2e/NonUniformGroups/fixed_size_group.cpp
We should probably rename the file as well. Also applies to `fixed_size_group_algorithms.cpp`

2024-10-16 14:50 UTC, AlexeySachkov commented on sycl/include/sycl/ext/oneapi/experimental/chunk.hpp
> +template <size_t PartitionSize, typename ParentGroup> class chunk {
```suggestion
template <size_t ChunkSize, typename ParentGroup> class chunk {
```

That's rather minor, but I think that it is better to be aligned in the terminology we use

2024-10-18 06:53 UTC, steffenlarsen commented
I am concerned about doing the changes in https://github.com/intel/llvm/pull/14604 gradually. I do not mind having multiple patches for them, but they should go in around the same time. We also need to make sure we coordinate these changes with changes to https://github.com/KhronosGroup/SYCL-CTS/tree/SYCL-2020/tests/extension/oneapi_non_uniform_groups.

2024-11-21 15:38 UTC, closed without merging