[SPIR-V] Update SPV_INTEL_function_pointers extension
intel/llvm pull request #2254
Opened 2020-08-04 15:44 UTC by zuban32

Replace OpFunctionPointerINTEL with a constant one

2020-08-04 15:53 UTC, AlexeySachkov commented on sycl/doc/extensions/SPIRV/SPV_INTEL_function_pointers.asciidoc
> +| 4 | ?? | '<id>' 'Result Type' | '<id> Result ' | '<id>' 'Function'
This change should be reverted, I guess

2020-08-04 17:27 UTC, zuban32 commented on sycl/doc/extensions/SPIRV/SPV_INTEL_function_pointers.asciidoc
> +| 4 | ?? | '<id>' 'Result Type' | '<id> Result ' | '<id>' 'Function'
Fixed

2020-08-11 08:31 UTC, AlexeySachkov commented
@intel/dpcpp-specification-reviewers, any feedback?

2020-10-14 12:45 UTC, bader commented
@intel/dpcpp-specification-reviewers, please, take a look.

2022-01-12 13:43 UTC, bader commented
@zuban32, could you resolve merge conflicts, please?

2022-01-26 06:33 UTC, bader commented
> @zuban32, could you resolve merge conflicts, please?

@zuban32, ping.

2022-02-07 11:24 UTC, AlexeySachkov requested changes
This PR should be superseded in favor of #4483 per my [comment](https://github.com/intel/llvm/pull/4883#issuecomment-1031354626) there

2022-09-06 02:15 UTC, closed without merging