[NFC][SYCL] Enable LIT for FPGA on Windows
intel/llvm pull request #2262
Opened 2020-08-05 06:42 UTC by vladimirlaz

The tests are enabled back as there were uplift of OpenCL RT for Intel FPGA emulator.

2020-08-07 13:08 UTC, vladimirlaz commented
The submission is blocked by the bug in OpenCL FPGA RT on Windows which causes sporadic crashes with the following backtrace. Waiting for the fix before submission.
```
0x000000A18D9F55D0  0x00007FFFBA98FA75 task_executor64_emu!RegisterGlobalAtExitNotification+0x10625
0x000000A18D9F5600  0x00007FFFBA987F4B task_executor64_emu!RegisterGlobalAtExitNotification+0x8afb
0x000000A18D9F5720  0x00007FFFBA986450 task_executor64_emu!RegisterGlobalAtExitNotification+0x7000
0x000000A18D9F5780  0x00007FFFBA9869E8 task_executor64_emu!RegisterGlobalAtExitNotification+0x7598
0x000000A18D9F57D0  0x00007FFFBA984559 task_executor64_emu!RegisterGlobalAtExitNotification+0x5109
0x000000A18D9F5800  0x00007FFFF81D477F ntdll!_chkstk+0x11f
0x000000A18D9F5F30  0x00007FFFF8134BEF ntdll!RtlWalkFrameChain+0x14bf
0x000000A18D9F66D0  0x00007FFFF81D34EE ntdll!KiUserExceptionDispatcher+0x2e
0x000000A18D9F67B0  0x00007FFFF4CC9129 KERNELBASE!RaiseException+0x69
0x000000A18D9F6820  0x00007FFFC9AD486D VCRUNTIME140!CxxThrowException+0xad
0x000000A18D9F6870  0x00007FFFBB4042F0 tbb!tbb::detail::r1::acquire_writer+0x11676
0x000000A18D9F68B0  0x00007FFFBA9626C8 task_executor64_emu+0x26c8
0x000000A18D9F68E0  0x00007FFFBA962D12 task_executor64_emu+0x2d12
0x000000A18D9F6920  0x00007FFFBA9620B7 task_executor64_emu+0x20b7
0x000000A18D9F6980  0x00007FFFBA965CD5 task_executor64_emu+0x5cd5
0x000000A18D9F69B0  0x00007FFFBA963014 task_executor64_emu+0x3014
0x000000A18D9F69F0  0x00007FFFBA962387 task_executor64_emu+0x2387
0x000000A18D9F6A20  0x00007FFFBA966008 task_executor64_emu+0x6008
0x000000A18D9F6A50  0x00007FFFBA9672ED task_executor64_emu+0x72ed
0x000000A18D9F6B50  0x00007FFFBB3F7D08 tbb!tbb::detail::r1::acquire_writer+0x508e
0x000000A18D9F6BB0  0x00007FFFBB4007EF tbb!tbb::detail::r1::acquire_writer+0xdb75
0x000000A18D9F6BE0  0x00007FFFBB40EA3E tbb!tbb::detail::r1::acquire_writer+0x1bdc4
0x000000A18D9F6C20  0x00007FFFBB4137D3 tbb!tbb::detail::r1::acquire_writer+0x20b59
0x000000A18D9FFC60  0x00007FFFBB413AAB tbb!tbb::detail::r1::acquire_writer+0x20e31
0x000000A18D9FFC90  0x00007FFFF4B91FFA ucrtbase!o_exp+0x5a
0x000000A18D9FFCC0  0x00007FFFF57D7974 KERNEL32!BaseThreadInitThunk+0x14
0x000000A18D9FFD40  0x00007FFFF819A271 ntdll!RtlUserThreadStart+0x21
```

2020-08-19 11:59 UTC, bader requested changes
Fix pre-commit failures.

2020-09-02 14:36 UTC, bader approved these changes

2020-09-02 14:40 UTC, romanovvlad approved these changes

2020-09-02 14:55 UTC, merged