[SYCL] Fix OpenCL version check when verifying SPIR-V online compilation support
intel/llvm pull request #2445
Opened 2020-09-09 01:04 UTC by dnmokhov

Extract major.minor substring from the full version string before comparison.

2020-09-09 05:23 UTC, kbobrovs requested changes

2020-09-09 05:23 UTC, kbobrovs commented on sycl/source/detail/program_manager/program_manager.cpp
> +  // All formats except PI_DEVICE_BINARY_TYPE_SPIRV are supported.
I think that decision whether a binary type is supported by a particular context or not should be made by plugin (or BE) decision associated with the context. Looks like we need a new PI function. Can you please add a TODO?

2020-09-09 05:23 UTC, kbobrovs commented on sycl/source/detail/program_manager/program_manager.cpp
> +    if ((VersionStringVector.size() > 1) && (VersionStringVector[1] >= "2.1"))
Lexicographical comparison is unreliable here. I guess "12.1" >= "2.1" would evaluate to false.

2020-09-17 10:54 UTC, s-kanaev approved these changes

2020-09-17 10:54 UTC, s-kanaev commented
@kbobrovs  ping

2020-09-17 11:02 UTC, kbobrovs approved these changes
I guess there are no versions like OpenCL 1.10, so this should work.

2020-09-17 14:15 UTC, merged