[SYCL] Fix hang in conditional variable pattern in program manager
intel/llvm pull request #2493
Opened 2020-09-18 16:31 UTC by alexanderfle

Signed-off-by: Alexander Flegontov <alexander.flegontov@intel.com>

2020-09-21 11:25 UTC, s-kanaev approved these changes
It's a shame we don't have test for this use-case.

2020-09-21 12:16 UTC, dm-vodopyanov commented on sycl/source/detail/program_manager/program_manager.cpp
> +      // Even if shared variable is atomic,it must be modified under the mutex
Minor: ```atomic,it``` -> ```atomic, it```

2020-09-21 12:16 UTC, dm-vodopyanov approved these changes

2020-09-21 12:21 UTC, kbobrovs requested changes
We've got quite a few issues related to cache management. But this complex piece still does not have a design doc. Can we please create a section on the caches in the main design doc or a separate document?

2020-09-21 12:29 UTC, s-kanaev commented
> Can we please create a section on the caches in the main design doc or a separate document?

Sorry, I forgot about this one. I will prepare the document.

2020-09-21 13:34 UTC, dm-vodopyanov approved these changes

2020-09-21 14:43 UTC, s-kanaev commented
> > Can we please create a section on the caches in the main design doc or a separate document?

> Sorry, I forgot about this one. I will prepare the document.

I mean, in distinct patch.

2020-09-21 14:48 UTC, alexanderfle commented
@kbobrovs , Since the design document will be added to a separate PR, could  you please review and approve the current PR?

2020-09-22 08:09 UTC, kbobrovs approved these changes

2020-09-22 08:18 UTC, merged