[SYCL] Fix bug with introp buffer
intel/llvm pull request #2637
Opened 2020-10-14 15:54 UTC by romanovvlad

Fixed a problem which happened when a buffer constructed using
interaperablity constructor with sycl::context A is used in a different
context.

2020-10-14 17:10 UTC, sergey-semenov requested changes
Seems like the assertion message and comment on https://github.com/intel/llvm/blob/2e9542a02419678dae0a2c1c2b827e2e878e7e2d/sycl/source/detail/memory_manager.cpp#L141 should be changed now, as this scenario is handled elsewhere.

2020-10-14 22:41 UTC, romanovvlad commented
/summary:run

2020-10-15 07:45 UTC, s-kanaev approved these changes

2020-10-15 08:19 UTC, sergey-semenov approved these changes

2020-10-15 15:26 UTC, merged