[SYCL] - Fix big and non-uniform work-groups handling in reduction ke…
intel/llvm pull request #2859
Opened 2020-12-03 23:23 UTC by v-klochkov

…rnels

This patch also does minor optimization in the main kernels created
for reductions. The previous code tried to handle non-uniform work-group sizes
and it did it wrong way. That code was removed as it is user's responsibility
to provide nd_range that is handled well by the devices, at least for
main kernels.

The patch conservatively limits the maximum work-group size handled by
the reduction implementation to avoid various runtime errors caused
by selecting too optimistic work-group size for reductions. This solution
is rather temporary until reduction kernels precompilation/query approach
is implemented.

Signed-off-by: Vyacheslav N Klochkov <vyacheslav.n.klochkov@intel.com>

2020-12-04 06:23 UTC, alexbatashev submitted a review, later dismissed
LGTM

2020-12-04 07:41 UTC, v-klochkov commented
> LGTM
Thank you. The new LIT test failed on ACC though and I need to tune heuristics there.

2020-12-04 17:20 UTC, Pennycook approved these changes

2020-12-04 17:29 UTC, bader requested changes
Please, fix CI failures.

2020-12-05 11:03 UTC, bader approved these changes

2020-12-05 11:21 UTC, alexbatashev approved these changes

2020-12-05 11:26 UTC, merged