[SYCL][GDB] Fix xmethod script for local accessors on Host
intel/llvm pull request #3203
Opened 2021-02-11 15:10 UTC by mihails-strasuns-intel

Previous version of script didn't take into account that local accessors
have a slightly different index calculation logic on Host and need to be
treated specially.

For Device the same script should still be applicable.

2021-02-11 16:14 UTC, alexbatashev approved these changes

2021-02-13 10:23 UTC, bader requested changes
@mihails-strasuns-intel, please, fix test failure on Linux.

2021-02-22 20:40 UTC, mihails-strasuns-intel commented
Sorry, got distracted. Test should be fixed now.

2021-02-24 06:54 UTC, alexbatashev approved these changes

2021-02-25 13:50 UTC, mihails-strasuns-intel commented
Ping, looks green now.

2021-03-01 11:40 UTC, mihails-strasuns-intel commented
Ping

2021-03-01 13:50 UTC, merged