[SYCL][FPGA] Update ArbitraryFloatCast functions API
intel/llvm pull request #3265
Opened 2021-02-25 16:00 UTC by mlychkov

Add a parameter that specifies if integer value to cast to/from
is signed or not.

See spec update: [SYCL] Floating point and fixed point operations added to SPIR-V (#1934)

Signed-off-by: Mikhail Lychkov <mikhail.lychkov@intel.com>

2021-02-25 18:14 UTC, MrSidims requested changes
We shall change
`_SPIRV_OP(CastFromInt, true, 8)`
to
`_SPIRV_OP(CastFromInt, true, 9)`
in the translator simultaneously with these changes (I mean create PR to https://github.com/KhronosGroup/SPIRV-LLVM-Translator and include the changes in this PR)

2021-02-26 14:13 UTC, mlychkov commented
> We shall change
> `_SPIRV_OP(CastFromInt, true, 8)`
> to
> `_SPIRV_OP(CastFromInt, true, 9)`
> in the translator simultaneously with these changes (I mean create PR to https://github.com/KhronosGroup/SPIRV-LLVM-Translator and include the changes in this PR)

Yes, thank you. Here is a PR for changes in SPIR-V translator: https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/925.

2021-02-26 16:01 UTC, MrSidims commented
I suggest not to wait a pull down and include those changes here as well (once https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/925/ is approved).

2021-03-30 07:31 UTC, mlychkov commented
> We shall change
> `_SPIRV_OP(CastFromInt, true, 8)`
> to
> `_SPIRV_OP(CastFromInt, true, 9)`
> in the translator simultaneously with these changes (I mean create PR to https://github.com/KhronosGroup/SPIRV-LLVM-Translator and include the changes in this PR)

@MrSidims SPIR-V update is merged into intel/llvm. Could you please review again?

2021-03-30 07:32 UTC, mlychkov commented
@romanovvlad Could you please review the patch?

2021-03-30 08:04 UTC, MrSidims approved these changes

2021-03-30 10:33 UTC, romanovvlad approved these changes

2021-03-30 12:27 UTC, merged