[SYCL] Support extra environment variables in LIT
intel/llvm pull request #3598
Opened 2021-04-22 11:10 UTC by vladimirlaz

Add ability to set extra environment variables in CMake (LIT_EXTRA_ENVIRONMENT)
or LIT (extra_environment) parameters. The value should contain comma separated
VARIABLE=VALUE pairs.

2021-04-22 21:54 UTC, smaslov-intel requested changes
LGTM. Just let's document this somewhere how to use it.

2021-04-23 04:21 UTC, vladimirlaz commented
> LGTM. Just let's document this somewhere how to use it.

The LIT infra for sycl/test is not documented. Will do that in separate PR.

2021-04-23 15:32 UTC, smaslov-intel commented
> Will do that in separate PR.

OK

2021-04-23 15:32 UTC, smaslov-intel approved these changes

2021-04-24 06:59 UTC, merged