Fix warning
intel/llvm pull request #3660
Opened 2021-04-29 19:09 UTC by smanna12

2021-04-29 20:16 UTC, AaronBallman requested changes
Why is it being initialized at all in the ctor? This is a `SmallVector` which default constructs just fine, but the constructor init list says `SYCLIntelFPGAVariantCount(false)` and I have no idea what that even *does*. :-D I think the correct fix is to remove the initialization from the ctor init list.

2021-04-29 21:21 UTC, zahiraam approved these changes

2021-04-30 13:38 UTC, AaronBallman approved these changes
LGTM!

2021-04-30 14:53 UTC, elizabethandrews approved these changes
Thanks!

2021-04-30 18:48 UTC, merged