[sycl-post-link] Fix the order of spec constants IDs in device image properties
intel/llvm pull request #3739
Opened 2021-05-12 16:43 UTC by vmaksimo

2021-05-12 17:12 UTC, AlexeySachkov approved these changes
LGTM

@dm-vodopyanov: FYI

2021-05-12 17:13 UTC, AlexeySachkov requested changes
But we should probably add a test

2021-05-14 15:47 UTC, AlexeySachkov approved these changes

2021-05-17 12:57 UTC, vmaksimo commented
Ping @rbegam

2021-05-17 17:33 UTC, rbegam approved these changes
LGTM

2021-05-17 19:15 UTC, merged

2021-05-18 08:43 UTC, bader commented on llvm/tools/sycl-post-link/SpecConstants.h
> +#include "llvm/ADT/MapVector.h"
Please, remove `#include <map>` from line 22.

2021-05-18 10:23 UTC, bader commented
@vmaksimo, this change introduced a regression to check-llvm tests. https://github.com/intel/llvm/runs/2604002244
Please, fix ASAP.

2021-05-26 07:40 UTC, AlexeySachkov commented
> @vmaksimo This patch also introduced llvm-dis as dependency for check-sycl target which is not defined in CMake files.
> Could you please remove that dependency or define it explicitly in https://github.com/intel/llvm/blob/sycl/sycl/test/CMakeLists.txt#L30
> 
> The problem is not exposed in CI because this dependency is built on preceding steps in test jobs.

I suggest that we remove the dependency, because it should be possible to write the test using text LLVM IR representation only

2021-05-26 09:48 UTC, vmaksimo commented
> I suggest that we remove the dependency, because it should be possible to write the test using text LLVM IR representation only

`llvm-spirv` does not accept LLVM IR as an input - so we should use either `llvm-dis` (as it's done now) or `llvm-as` to run `llvm-spirv`.

2021-05-26 09:59 UTC, AlexeySachkov commented
> > I suggest that we remove the dependency, because it should be possible to write the test using text LLVM IR representation only
> 
> `llvm-spirv` does not accept LLVM IR as an input - so we should use either `llvm-dis` (as it's done now) or `llvm-as` to run `llvm-spirv`.

Since we do not check generated SPIR-V I think we can avoid launching `llvm-spirv` in that test.

2021-05-26 10:08 UTC, vmaksimo commented
Removed dependency in https://github.com/intel/llvm/pull/3821