[ESIMD] rename gather4/scatter4 to gather_rgba/scatter_rgba
intel/llvm pull request #4120
Opened 2021-07-16 05:45 UTC by DenisBakhvalov

2021-07-16 17:00 UTC, kbobrovs approved these changes

2021-07-16 17:07 UTC, kbobrovs requested changes
hit approve prematurely :)
there are also slm_load4/slm_store4 versions  which have to be renamed as well

2021-07-16 17:57 UTC, DenisBakhvalov commented
> hit approve prematurely :)
> there are also slm_load4/slm_store4 versions which have to be renamed as well

I would prefer to do it in a separate PR if you don’t mind.

2021-07-17 15:32 UTC, kbobrovs commented
> > hit approve prematurely :)
> > there are also slm_load4/slm_store4 versions which have to be renamed as well
> 
> I would prefer to do it in a separate PR if you don’t mind.

OK

2021-07-17 15:32 UTC, kbobrovs submitted a review, later dismissed

2021-07-17 18:43 UTC, kychendev approved these changes

2021-07-19 19:11 UTC, kbobrovs approved these changes

2021-07-19 19:12 UTC, merged