[SYCL] Add SYCL2020 buffer and vec function byte_size()
intel/llvm pull request #4141
Opened 2021-07-19 14:35 UTC by nawrinsu

2021-07-19 18:21 UTC, bader commented on sycl/include/CL/sycl/types.hpp
> +  size_t get_size() const { return byte_size(); }
I think `get_size` must be a template to avoid potential ABI breaks. Right?

2021-08-10 10:03 UTC, vladimirlaz requested changes
Could you please add tests for new functions?
Also you can add checks for deprecation messages in sycl/test/warnings/sycl_2020_deprecations.cpp.

2021-08-12 23:31 UTC, nawrinsu commented
PR link for test - https://github.com/intel/llvm-test-suite/pull/403

2021-08-13 09:25 UTC, vladimirlaz approved these changes

2021-08-16 04:07 UTC, vladimirlaz commented
@turinevgeny could you please review as the code owner?

2021-08-16 07:17 UTC, turinevgeny approved these changes

2021-08-16 09:25 UTC, bader approved these changes

2021-08-16 10:11 UTC, merged