[BuildBot] Uplift GPU RT version for Linux CI Process
intel/llvm pull request #4342
Opened 2021-08-15 12:15 UTC by bb-sycl

Uplift GPU RT version for Linux to 21.32.20609

2021-08-16 13:19 UTC, bader requested changes
The driver update introduces a regression. Is there other version, which doesn't regress SYCL tests?

2021-08-20 10:59 UTC, vladimirlaz approved these changes

2021-08-20 11:01 UTC, bader commented
/summary:run

2021-08-20 16:46 UTC, bader approved these changes

2021-08-20 16:47 UTC, merged