[SYCL] Correction to accessor range indexing.
intel/llvm pull request #4556
Opened 2021-09-13 20:53 UTC by rdeodhar

Corrected a typo in the accessor header file.

Signed-off-by: rdeodhar <rajiv.deodhar@intel.com>

2021-09-13 21:11 UTC, bader reviewed
I think we need to cover this code with tests.

2021-09-16 06:34 UTC, vladimirlaz submitted a review, later dismissed

2021-09-16 14:48 UTC, romanovvlad commented
> 
> 
> I think we need to cover this code with tests.

@rdeodhar Could you please add a test?

2021-09-21 09:19 UTC, romanovvlad commented on sycl/include/CL/sycl/accessor.hpp
> +    return range<3>(Range[0], Range[1], Range[2]);
@rdeodhar Could you please add a test?

2021-09-21 09:19 UTC, romanovvlad requested changes

2021-09-21 09:19 UTC, romanovvlad commented on sycl/include/CL/sycl/accessor.hpp
> -    return range<3>(Range[0], Range[1], Range[3]);
@rdeodhar Could you please add a test?

2021-09-22 09:54 UTC, romanovvlad commented on sycl/test/basic_tests/image_accessor_range.cpp
> +// RUN: %GPU_RUN_PLACEHOLDER %t.out %GPU_CHECK_PLACEHOLDER
Please, move the test to  `llvm-test-suite` repo since it has dependencies on low-level runtimes.

2021-09-22 18:10 UTC, rdeodhar commented
The test for image ranges has been added to llvm_test_suite. It will fail there until this PR is merged.

2021-09-23 05:36 UTC, vladimirlaz approved these changes

2021-09-23 09:07 UTC, romanovvlad approved these changes

2021-09-23 09:09 UTC, merged