[SYCL] Add HIP arch argument for lit tests
intel/llvm pull request #4676
Opened 2021-09-30 14:34 UTC by AidanBeltonS

When using the HIP backend for an AMD platform the gpu's architecture must be sepcified with `-Xsycl-target-backend=amdgcn-amd-amdhsa --offload-arch=<target>`. This patch adds an option to `buildbot/configure.py` which allows the user to state the gpu architecture for lit tests when running `check-sycl-hip`. 
Relevant messages and docs are updated within the patch.

2021-09-30 14:47 UTC, alexbatashev requested changes
Why do we need this patch? All tests that require real hardware must go to intel/llvm-test-suite repo.

2021-09-30 14:52 UTC, AidanBeltonS commented
Regardless of running the test on real hardware you must specify the amd-arch to compile anything when targetting `amdgcn-amd-amdhsa`. So the patch is necessary even if no on-device tests are run.

2021-09-30 14:58 UTC, alexbatashev approved these changes
@AidanBeltonS please add this info to PR description

2021-10-04 05:43 UTC, bader approved these changes

2021-10-04 05:45 UTC, merged