[SYCL] Define SYCL_DISABLE_FALLBACK_ASSERT macro
intel/llvm pull request #4824
Opened 2021-10-26 21:45 UTC by elizabethandrews

Define SYCL_DISABLE_FALLBACK_ASSERT for FPGA

Signed-off-by: Elizabeth Andrews <elizabeth.andrews@intel.com>

2021-11-24 14:35 UTC, s-kanaev commented on clang/lib/Frontend/InitPreprocessor.cpp
> +      Builder.defineMacro("SYCL_DISABLE_FALLBACK_ASSERT");
@bader , @elizabethandrews 
There's a plan to re-enable fallback assert by default.
Hence, I've re-opened PR.

2021-11-26 08:34 UTC, dm-vodopyanov commented on clang/lib/Frontend/InitPreprocessor.cpp
> +      Builder.defineMacro("SYCL_DISABLE_FALLBACK_ASSERT");
@s-kanaev , is some additional work expected in this PR? Can the PR be merged?

2021-11-26 09:05 UTC, s-kanaev commented on clang/lib/Frontend/InitPreprocessor.cpp
> +      Builder.defineMacro("SYCL_DISABLE_FALLBACK_ASSERT");
I'll check with @elizabethandrews  what sort of test should be added here.

2021-11-26 15:24 UTC, smanna12 requested changes
>>Can you add test?

Tests have been already added. Sorry I missed that.

2021-11-26 15:29 UTC, smanna12 approved these changes

2021-11-29 12:25 UTC, s-kanaev commented
@premanandrao , a friendly ping

2021-11-29 13:39 UTC, bader commented on clang/lib/Frontend/InitPreprocessor.cpp
> +      Builder.defineMacro("SYCL_DISABLE_FALLBACK_ASSERT");
@s-kanaev, what is overall plan for fallback assert? Are we going to commit #4824 and close #4694?

2021-11-29 14:03 UTC, s-kanaev commented on clang/lib/Frontend/InitPreprocessor.cpp
> +      Builder.defineMacro("SYCL_DISABLE_FALLBACK_ASSERT");
Absolutely, #4694 is going to be closed. #4824 and #4780 are going to be committed. There were two types of issues:
 * enabling assertions for interop kernels
 * impact of assertions on FPGA
The former is fixed in #4712.
The latter is fixed with help of #4824 and #4780.

2021-11-29 14:10 UTC, bader commented on clang/lib/Frontend/InitPreprocessor.cpp
> +      Builder.defineMacro("SYCL_DISABLE_FALLBACK_ASSERT");
I think the second issue impacts non-FPGA devices as well. AFAIK, additional assert-specific device code is emitted for all devices even though assert is not used. Is it right? If so, what is the plan to address the overhead associated with the additional code?

2021-11-29 14:21 UTC, s-kanaev commented on clang/lib/Frontend/InitPreprocessor.cpp
> +      Builder.defineMacro("SYCL_DISABLE_FALLBACK_ASSERT");
> AFAIK, additional assert-specific device code is emitted for all devices even though assert is not used. Is it right?
Yes.
To overcome this impact I need to do some refactoring which is a bit stuck at limitations of sycl-post-link tool.
The limitation could be handled with employing of `__sycl_kernel` attribute, though, it requires for the function to be template which isn't acceptable at the moment. Also, @AlexeySachkov  can't approve the w/a in sycl-post-link I presented to him.
The overall idea of refactoring can be caught with changes of devicelib in #4987.

2021-11-29 17:50 UTC, elizabethandrews commented on clang/lib/Frontend/InitPreprocessor.cpp
> +      Builder.defineMacro("SYCL_DISABLE_FALLBACK_ASSERT");
> 

There is a test in this patch for the macro. From a FE perspective, I don't think further tests are required

2021-11-29 17:52 UTC, elizabethandrews commented
> I'll check with @elizabethandrews what sort of test should be added here

There is a test in this patch for the macro. From a FE perspective, I don't think further tests are required

2021-11-29 18:22 UTC, bader commented on clang/lib/Frontend/InitPreprocessor.cpp
> +      Builder.defineMacro("SYCL_DISABLE_FALLBACK_ASSERT");
Please, follow https://chris.beams.io/posts/git-commit/ and add proper PR title and description to #4987.

2021-11-29 18:23 UTC, bader approved these changes

2021-11-29 21:42 UTC, premanandrao approved these changes
LGTM

2021-11-30 09:45 UTC, merged