[SYCL][build scripts] Add option to set compile target
intel/llvm pull request #5024
Opened 2021-11-24 13:15 UTC by vmaksimo

Sometimes you don't need to build all the SYCL toolchain - added option to set
the needed build target.

2021-11-24 14:13 UTC, bader reviewed
@vmaksimo, please, add option description to the GetStartedGuide.

2021-11-24 16:47 UTC, vladimirlaz requested changes

2021-11-24 16:47 UTC, vladimirlaz commented on sycl/doc/GetStartedGuide.md
> +* `-t` -> Build target (e.g., `clang` or `llvm-spirv`). Default is `deploy-sycl-toolchain`
```suggestion
* `-t`, "--build-target" -> Build target (e.g., `clang` or `llvm-spirv`). Default is `deploy-sycl-toolchain`
```

2021-11-25 05:20 UTC, vladimirlaz approved these changes

2021-11-25 06:26 UTC, bader approved these changes

2021-11-25 06:26 UTC, merged