[SYCL][CUDA][libclc] Fixes atomics for bellow sm_60
intel/llvm pull request #5025
Opened 2021-11-24 16:06 UTC by t4c1

Fixes #5008. Fixes libclc implementation of CUDA atomics by using `__nvvm_reflect()` so as not to emit intrinsics that are unsupported on target sm version. If atomics are called with semantic order or scope that is not supported, `__builtin_trap()` is called instead.

2021-11-24 16:37 UTC, bader approved these changes

2021-11-24 16:40 UTC, bader commented
/verify with https://github.com/intel/llvm-test-suite/pull/581

2021-11-25 07:03 UTC, bader commented
`Basic/scalar_vec_access.cpp` and `Basic/stream/stream.cpp` tests from https://github.com/intel/llvm-test-suite/ are failing with this change:
```
[2021-11-24T18:52:01.806Z] ******************** TEST 'LLVM :: Basic/scalar_vec_access.cpp' FAILED ********************
[2021-11-24T18:52:01.806Z] Script:
[2021-11-24T18:52:01.806Z] --
[2021-11-24T18:52:01.806Z] : 'RUN: at line 1';    /localdisk2/iusers/nstester/Codeplay/workspace/LLVM_CI/intel/Lin/LLVM_Test_Suite_CUDA/llvm.obj/bin/clang++      -fLLVM -fLLVM-targets=nvptx64-nvidia-cuda /localdisk2/iusers/nstester/Codeplay/workspace/LLVM_CI/intel/Lin/LLVM_Test_Suite_CUDA/llvm-test-suite/LLVM/Basic/scalar_vec_access.cpp -o /localdisk2/iusers/nstester/Codeplay/workspace/LLVM_CI/intel/Lin/LLVM_Test_Suite_CUDA/build/LLVM/Basic/Output/scalar_vec_access.cpp.tmp.out
[2021-11-24T18:52:01.806Z] : 'RUN: at line 2';   true /localdisk2/iusers/nstester/Codeplay/workspace/LLVM_CI/intel/Lin/LLVM_Test_Suite_CUDA/build/LLVM/Basic/Output/scalar_vec_access.cpp.tmp.out
[2021-11-24T18:52:01.806Z] : 'RUN: at line 3';   true /localdisk2/iusers/nstester/Codeplay/workspace/LLVM_CI/intel/Lin/LLVM_Test_Suite_CUDA/build/LLVM/Basic/Output/scalar_vec_access.cpp.tmp.out
[2021-11-24T18:52:01.806Z] : 'RUN: at line 4';    env LLVM_DEVICE_FILTER=cuda:gpu,host  /localdisk2/iusers/nstester/Codeplay/workspace/LLVM_CI/intel/Lin/LLVM_Test_Suite_CUDA/build/LLVM/Basic/Output/scalar_vec_access.cpp.tmp.out | FileCheck /localdisk2/iusers/nstester/Codeplay/workspace/LLVM_CI/intel/Lin/LLVM_Test_Suite_CUDA/llvm-test-suite/LLVM/Basic/scalar_vec_access.cpp
[2021-11-24T18:52:01.806Z] : 'RUN: at line 5';   true /localdisk2/iusers/nstester/Codeplay/workspace/LLVM_CI/intel/Lin/LLVM_Test_Suite_CUDA/build/LLVM/Basic/Output/scalar_vec_access.cpp.tmp.out
[2021-11-24T18:52:01.806Z] --
[2021-11-24T18:52:01.806Z] Exit Code: 255
[2021-11-24T18:52:01.806Z] 
[2021-11-24T18:52:01.806Z] Command Output (stdout):
[2021-11-24T18:52:01.806Z] --
[2021-11-24T18:52:01.806Z] $ ":" "RUN: at line 1"
[2021-11-24T18:52:01.806Z] note: command had no output on stdout or stderr
[2021-11-24T18:52:01.806Z] $ "/localdisk2/iusers/nstester/Codeplay/workspace/LLVM_CI/intel/Lin/LLVM_Test_Suite_CUDA/llvm.obj/bin/clang++" "-fLLVM" "-fLLVM-targets=nvptx64-nvidia-cuda" "/localdisk2/iusers/nstester/Codeplay/workspace/LLVM_CI/intel/Lin/LLVM_Test_Suite_CUDA/llvm-test-suite/LLVM/Basic/scalar_vec_access.cpp" "-o" "/localdisk2/iusers/nstester/Codeplay/workspace/LLVM_CI/intel/Lin/LLVM_Test_Suite_CUDA/build/LLVM/Basic/Output/scalar_vec_access.cpp.tmp.out"
[2021-11-24T18:52:01.806Z] # command stderr:
[2021-11-24T18:52:01.806Z] warning: linking module '/localdisk2/iusers/nstester/Codeplay/workspace/LLVM_CI/intel/Lin/LLVM_Test_Suite_CUDA/llvm.obj/lib/clang/14.0.0/../../clc/remangled-l64-signed_char.libspirv-nvptx64--nvidiacl.bc': Linking two modules of different target triples: '/localdisk2/iusers/nstester/Codeplay/workspace/LLVM_CI/intel/Lin/LLVM_Test_Suite_CUDA/llvm.obj/lib/clang/14.0.0/../../clc/remangled-l64-signed_char.libspirv-nvptx64--nvidiacl.bc' is 'nvptx64-unknown-nvidiacl' whereas '/localdisk2/iusers/nstester/Codeplay/workspace/LLVM_CI/intel/Lin/LLVM_Test_Suite_CUDA/llvm-test-suite/LLVM/Basic/scalar_vec_access.cpp' is 'nvptx64-nvidia-cuda'
[2021-11-24T18:52:01.806Z]  [-Wlinker-warnings]
[2021-11-24T18:52:01.806Z] 1 warning generated.
[2021-11-24T18:52:01.806Z] ptxas fatal   : Unresolved extern function '__nvvm_reflect'
[2021-11-24T18:52:01.806Z] llvm-foreach: 
[2021-11-24T18:52:01.806Z] clang-14: error: ptxas command failed with exit code 255 (use -v to see invocation)
[2021-11-24T18:52:01.806Z] Target: x86_64-unknown-linux-gnu
[2021-11-24T18:52:01.806Z] Thread model: posix
[2021-11-24T18:52:01.806Z] InstalledDir: /localdisk2/iusers/nstester/Codeplay/workspace/LLVM_CI/intel/Lin/LLVM_Test_Suite_CUDA/llvm.obj/bin
[2021-11-24T18:52:01.806Z] clang-14: note: diagnostic msg: Error generating preprocessed source(s).
[2021-11-24T18:52:01.806Z] 
[2021-11-24T18:52:01.806Z] error: command failed with exit status: 255
[2021-11-24T18:52:01.806Z] 
[2021-11-24T18:52:01.806Z] --
[2021-11-24T18:52:01.806Z] 
[2021-11-24T18:52:01.806Z] ********************
```

```
[2021-11-24T18:52:12.821Z] ******************** TEST 'LLVM :: Basic/stream/stream.cpp' FAILED ********************
[2021-11-24T18:52:12.821Z] Script:
[2021-11-24T18:52:12.821Z] --
[2021-11-24T18:52:12.821Z] : 'RUN: at line 1';    /localdisk2/iusers/nstester/Codeplay/workspace/LLVM_CI/intel/Lin/LLVM_Test_Suite_CUDA/llvm.obj/bin/clang++      -fLLVM -fLLVM-targets=nvptx64-nvidia-cuda /localdisk2/iusers/nstester/Codeplay/workspace/LLVM_CI/intel/Lin/LLVM_Test_Suite_CUDA/llvm-test-suite/LLVM/Basic/stream/stream.cpp -o /localdisk2/iusers/nstester/Codeplay/workspace/LLVM_CI/intel/Lin/LLVM_Test_Suite_CUDA/build/LLVM/Basic/stream/Output/stream.cpp.tmp.out
[2021-11-24T18:52:12.821Z] : 'RUN: at line 4';   true /localdisk2/iusers/nstester/Codeplay/workspace/LLVM_CI/intel/Lin/LLVM_Test_Suite_CUDA/build/LLVM/Basic/stream/Output/stream.cpp.tmp.out
[2021-11-24T18:52:12.821Z] : 'RUN: at line 5';   env LLVM_DEVICE_FILTER=cuda:gpu,host  /localdisk2/iusers/nstester/Codeplay/workspace/LLVM_CI/intel/Lin/LLVM_Test_Suite_CUDA/build/LLVM/Basic/stream/Output/stream.cpp.tmp.out | FileCheck /localdisk2/iusers/nstester/Codeplay/workspace/LLVM_CI/intel/Lin/LLVM_Test_Suite_CUDA/llvm-test-suite/LLVM/Basic/stream/stream.cpp
[2021-11-24T18:52:12.821Z] : 'RUN: at line 6';   true /localdisk2/iusers/nstester/Codeplay/workspace/LLVM_CI/intel/Lin/LLVM_Test_Suite_CUDA/build/LLVM/Basic/stream/Output/stream.cpp.tmp.out
[2021-11-24T18:52:12.821Z] --
[2021-11-24T18:52:12.821Z] Exit Code: 255
[2021-11-24T18:52:12.821Z] 
[2021-11-24T18:52:12.821Z] Command Output (stdout):
[2021-11-24T18:52:12.821Z] --
[2021-11-24T18:52:12.821Z] $ ":" "RUN: at line 1"
[2021-11-24T18:52:12.821Z] note: command had no output on stdout or stderr
[2021-11-24T18:52:12.821Z] $ "/localdisk2/iusers/nstester/Codeplay/workspace/LLVM_CI/intel/Lin/LLVM_Test_Suite_CUDA/llvm.obj/bin/clang++" "-fLLVM" "-fLLVM-targets=nvptx64-nvidia-cuda" "/localdisk2/iusers/nstester/Codeplay/workspace/LLVM_CI/intel/Lin/LLVM_Test_Suite_CUDA/llvm-test-suite/LLVM/Basic/stream/stream.cpp" "-o" "/localdisk2/iusers/nstester/Codeplay/workspace/LLVM_CI/intel/Lin/LLVM_Test_Suite_CUDA/build/LLVM/Basic/stream/Output/stream.cpp.tmp.out"
[2021-11-24T18:52:12.821Z] # command stderr:
[2021-11-24T18:52:12.821Z] warning: linking module '/localdisk2/iusers/nstester/Codeplay/workspace/LLVM_CI/intel/Lin/LLVM_Test_Suite_CUDA/llvm.obj/lib/clang/14.0.0/../../clc/remangled-l64-signed_char.libspirv-nvptx64--nvidiacl.bc': Linking two modules of different target triples: '/localdisk2/iusers/nstester/Codeplay/workspace/LLVM_CI/intel/Lin/LLVM_Test_Suite_CUDA/llvm.obj/lib/clang/14.0.0/../../clc/remangled-l64-signed_char.libspirv-nvptx64--nvidiacl.bc' is 'nvptx64-unknown-nvidiacl' whereas '/localdisk2/iusers/nstester/Codeplay/workspace/LLVM_CI/intel/Lin/LLVM_Test_Suite_CUDA/llvm-test-suite/LLVM/Basic/stream/stream.cpp' is 'nvptx64-nvidia-cuda'
[2021-11-24T18:52:12.821Z]  [-Wlinker-warnings]
[2021-11-24T18:52:12.821Z] 1 warning generated.
[2021-11-24T18:52:12.821Z] ptxas fatal   : Unresolved extern function '__nvvm_reflect'
[2021-11-24T18:52:12.821Z] llvm-foreach: 
[2021-11-24T18:52:12.821Z] clang-14: error: ptxas command failed with exit code 255 (use -v to see invocation)
[2021-11-24T18:52:12.821Z] Target: x86_64-unknown-linux-gnu
[2021-11-24T18:52:12.821Z] Thread model: posix
[2021-11-24T18:52:12.821Z] InstalledDir: /localdisk2/iusers/nstester/Codeplay/workspace/LLVM_CI/intel/Lin/LLVM_Test_Suite_CUDA/llvm.obj/bin
[2021-11-24T18:52:12.821Z] clang-14: note: diagnostic msg: Error generating preprocessed source(s).
[2021-11-24T18:52:12.821Z] 
[2021-11-24T18:52:12.821Z] error: command failed with exit status: 255
[2021-11-24T18:52:12.821Z] 
[2021-11-24T18:52:12.821Z] --
[2021-11-24T18:52:12.821Z] 
[2021-11-24T18:52:12.821Z] ********************
```

It looks like we need to run `NVVM [...]

2021-11-25 07:04 UTC, bader requested changes
Please, fix `ptxas fatal   : Unresolved extern function '__nvvm_reflect'` issue.

2021-11-30 12:32 UTC, bader commented on libclc/ptx-nvidiacl/libspirv/group/collectives.cl
> +    if (__clc_nvvm_reflect_arch() >= 800 && op == Reduce) {                      \
```suggestion
    if (__clc_nvvm_reflect_arch() >= 800 && op == Reduce) {                    \
```

2021-11-30 12:35 UTC, t4c1 commented
So it looks like calling `__nvvm_reflect` from OpenCL is a bit broken. `__nvvm_reflect` requires an argument of type `char*`, while in OpenCL strings are in `__constant` AS. So we were declaring `__nvvm_reflect(__constant char*)`, which works for uses in libclc, but breaks the uses of reflect in libdevice. I fixed this by declaring the string for reflect in IR instead.

2021-11-30 12:41 UTC, bader commented
/verify with https://github.com/intel/llvm-test-suite/pull/590

2021-12-02 09:20 UTC, bader approved these changes

2021-12-02 17:17 UTC, merged