[SYCL][CUDA][PI] Add CUDA-specific pi_mem_advice values
intel/llvm pull request #5090
Opened 2021-12-06 10:45 UTC by t4c1

Add CUDA-specific pi_mem_advice values and implement support for them in PI.

2021-12-06 12:39 UTC, steffenlarsen requested changes
Nice addition but we should be consistent with other implementations.

2021-12-06 12:39 UTC, steffenlarsen commented on sycl/plugins/cuda/pi_cuda.cpp
> +          -1));
```suggestion
          CU_DEVICE_CPU));
```

2021-12-06 12:39 UTC, steffenlarsen commented on sycl/include/CL/sycl/detail/pi.h
> +  PI_MEM_ADVISE_CUDA_UNSET_ACCESSED_BY_HOST = 10,
These are all CUDA specific, however most other PI enums are built around the OpenCL counter-part. Granted there are no OpenCL descriptors yet, I would still prefer that the CUDA-specific options are moved to start at a number that isn't 1 as we should leave some buffer for OpenCL descriptors in the future.

2022-02-01 14:45 UTC, AerialMantis commented
@steffenlarsen @smaslov-intel could we get another review on this one please.

2022-02-01 15:09 UTC, steffenlarsen approved these changes
LGTM! Sorry for the delay.

2022-02-01 15:18 UTC, smaslov-intel commented on sycl/include/CL/sycl/detail/pi.h
> +  PI_MEM_ADVISE_UNKNOWN,
NIT: to follow PI API notation and repeat enum typename:
```suggestion
  PI_MEM_ADVIcE_UNKNOWN,
```

2022-02-03 14:10 UTC, steffenlarsen approved these changes

2022-02-03 14:11 UTC, bader commented
/verify with https://github.com/intel/llvm-test-suite/pull/602

2022-02-04 12:16 UTC, bader commented
/verify with https://github.com/intel/llvm-test-suite/pull/602

2022-02-04 12:16 UTC, bader approved these changes

2022-02-06 11:11 UTC, bader commented
[2022-02-04T14:18:47.318Z] Failed Tests (2):
[2022-02-04T14:18:47.318Z]   SYCL :: DiscardEvents/discard_events_usm.cpp
[2022-02-04T14:18:47.318Z]   SYCL :: DiscardEvents/discard_events_usm_ooo_queue.cpp

@t4c1, it looks like these tests should be updated as well.

2022-02-08 15:47 UTC, t4c1 commented
The tests are now updated.

2022-02-08 16:01 UTC, bader commented
/verify with https://github.com/intel/llvm-test-suite/pull/602

2022-02-09 16:07 UTC, merged