[SYCL] Fix corner case: USM, 2nd CG depends_on 1st
intel/llvm pull request #5098
Opened 2021-12-07 13:22 UTC by dm-vodopyanov

This patch fixes corner case where during USM, there are two CGs
from two different queues, and second CG `depends_on` first CG. There
are no memory dependencies between these two CGs. Without this patch,
kernel from second CG didn't run. This is happened because command which
doesn't have dependencies (due to USM) and users is cleaned up in the
wrong place which led to failed command enqueueing. We don't have memory
leak here because this command is cleaned up in `handleVisitedNodes`
function in graph_builder.cpp.

Test in intel/llvm-test-suite TBA

2021-12-07 13:40 UTC, steffenlarsen commented
Looks good. Would you mind changing the comment on the success-case use of `CleanUp`? It does not seem in line with the changes.

2021-12-07 15:57 UTC, sergey-semenov requested changes
Discussed this change separately. It's not clear right now why the deletion of the first ExecCG command leads to any issues here, since its users should only refer to the event provided with depends_on rather than the command itself (since Event->MCommand is set to nullptr during deletion). I'm also worried that this change leaves us with memory leaks for commands with no  implicit dependencies if the user doesn't call queue/event::wait for them (which is what CleanUp() was initially supposed to address).

2021-12-09 16:59 UTC, dm-vodopyanov commented
/summary:run

2021-12-09 17:04 UTC, dm-vodopyanov commented
/summary:run

2021-12-10 10:47 UTC, steffenlarsen commented on sycl/source/detail/scheduler/scheduler.cpp
> +        assert(NewCmd->isSuccessfullyEnqueued());
If this is a requirement for the cleanup to do anything, does it make sense to call it from the fail-cases? Most often they will report `EnqueueResultT::SyclEnqueueFailed` and thus not report the command as having been enqueued succesfully.

2023-02-05 02:05 UTC, closed without merging