[SYCL][FPGA] Add new argument to __spirv_ArbitraryFloatPowNINTEL
intel/llvm pull request #5170
Opened 2021-12-17 12:10 UTC by mlychkov

Signed-off-by: Mikhail Lychkov <mikhail.lychkov@intel.com>

2021-12-20 11:51 UTC, vmaksimo approved these changes

2021-12-20 12:02 UTC, MrSidims requested changes
Expressing concerns internally

2021-12-21 09:25 UTC, MrSidims approved these changes

2021-12-27 11:15 UTC, vmaksimo commented
Need a review/approval from @intel/llvm-reviewers-runtime

2021-12-27 11:36 UTC, sergey-semenov approved these changes

2021-12-27 12:54 UTC, merged