[SYCL][XPTI] Add kernel-accessor association
intel/llvm pull request #5259
Opened 2022-01-04 17:03 UTC by vladimirlaz

2022-01-04 18:32 UTC, vladimirlaz commented
/verify with intel/llvm-test-suite#703

2022-01-10 05:34 UTC, vladimirlaz commented
The failures are expected and the tests updated accordingly have passed: Jenkins/verify-test-suite-logs

2022-01-10 06:20 UTC, alexbatashev requested changes
We already expose this info via [edge_create](https://intel.github.io/llvm-docs/SYCLInstrumentationUsingXPTI.html#sycl-stream-sycl-notification-signatures) tracepoint. Why is this duplication needed?

2022-01-31 08:18 UTC, alexbatashev reviewed
@vladimirlaz please provide the description and make sure the title of this PR matches its content

2022-01-31 08:18 UTC, alexbatashev commented on sycl/source/detail/xpti_registry.cpp
> +      CodeLoc.lineNumber(), CodeLoc.columnNumber(), const_cast<void *>(Obj));
Is it better to update this in XPTI directly, so that it stores a const pointer?

2022-01-31 10:59 UTC, alexbatashev approved these changes

2022-01-31 14:44 UTC, merged