[SYCL][DOC][FP19]Extension proposal for fp19 (tf32) class/conversions
intel/llvm pull request #5295
Opened 2022-01-12 18:44 UTC by JackAKirk

This extension proposal copies almost exactly the extension proposal for the bfloat16 class "SYCL_INTEL_bf16_conversion" authored by @AlexeySotkin.  If this proposal is also eventually merged then it should really have their name as author.

I will summarize the differences with respect to the existing bfloat16 proposal here:

- fp19 uses uint32_t as the storage type (bfloat16 uses uint16_t).

- The oneapi namespace is used instead of the intel namespace: it is expected that both the Intel and CUDA backends can implement this extension.

- The conversion from float to fp19 is done with rounds to nearest (odd or even), ties away from zero(RNA) rounding mode.  This rounding mode is used since it is the only one supported natively by Nvidia ptx asm.

- The Nvidia backend only natively supports conversion from float to fp19, not the other way around.  Therefore the only implementation specialization required by the Nvidia backend will be for the member function: `static storage_t from_float(const float &a)`.  This function implementation will call the `__nvvm_f2tf32_rna` builtin to perform the float to fp19 conversion.

- As far as I currently understand it, all other details can match those of the existing bfloat16 proposal (with "fp19" replacing "bfloat16" where appropriate).
  

Note that fp19 is named "tf32" in the Nvidia ptx asm.  A point for discussion is whether "fp19" is the best name for this data format or whether an alternative name is preferred.

The other question is whether the Intel backend will also make use of this proposal.  I'm assuming this is the case.  If not I can add the [CUDA] label.

2022-01-13 09:58 UTC, keryell requested changes
Interesting.

2022-01-13 09:58 UTC, keryell commented on sycl/doc/extensions/fp19Conversion/SYCL_fp19_conversion.asciidoc
> +| `friend fp19 operator-(fp19 &val) { /* ... */ }`
I guess we should also have
```c++
friend fp19 operator+(fp19 &val)`
```
It was also forgotten in the spec up to recently :-) https://www.khronos.org/registry/SYCL/specs/sycl-2020/html/sycl-2020.html#_vec_interface

2022-01-13 09:58 UTC, keryell commented on sycl/doc/extensions/fp19Conversion/SYCL_fp19_conversion.asciidoc
> +using sycl::ext::oneapi::experimental::fp19;
```suggestion
using sycl::ext::oneapi::experimental;
```
?

2022-01-13 09:58 UTC, keryell commented on sycl/doc/extensions/fp19Conversion/SYCL_fp19_conversion.asciidoc
> +
```suggestion
```
Redefinition?

2022-01-13 09:58 UTC, keryell commented on sycl/doc/extensions/fp19Conversion/SYCL_fp19_conversion.asciidoc
> +      cgh.single_task<class simple_kernel> ([=] () {
```suggestion
      sycl ::accessor numbers { buf, cgh };
      cgh.single_task<class simple_kernel> ([=] {
```

2022-01-17 09:46 UTC, JackAKirk commented
> Interesting.

Thanks for the comments.

I should also point out that there is another option (instead of introducing this "fp19" class) to represent the fp19 data format:  Unlike the bf16 data format, fp19 can be stored using float (at least for the user facing part).  This would work as follows:
We introduce a new free function for converting to the fp19 data format; this function takes a float and returns a float holding the fp19 format.  

An advantage of allowing the user to use float to hold the fp19 format is that it could mean fewer lines to change for users that have code using float and wishing to take advantage of the better fp19 performance.

A disadvantage would be that the user has to remember that once they have converted to float to "fp19", they can no longer use the float as a normal float: they have to remember to do a conversion of the fp19 float back to fp32 float.  Using the fp19 class makes this explicit and is much clearer.

I think that using the fp19 class (similarly to the Intel bfloat16 class) is the better option, but it would be good to reach a consensus on this before moving forward.  What do you think?

2022-01-25 18:24 UTC, JackAKirk commented
> 
> I think that using the fp19 class (similarly to the Intel bfloat16 class) is the better option, but it would be good to reach a consensus on this before moving forward. What do you think?

It is worth mentioning that it would be possible to implement both cases: a fp19 (alternative name: bfloat19) class, and a conversion function that takes a float and returns a float with fp19 precision.  However it could be argued that having these two different options could prove confusing to users.  If it is preferred that we pick only one of these options then it would be better to make this decision sooner rather than later, since we plan on pushing fp19 support imminently.

A strong argument for the option of always using floats is that a big reason for using tf32 instead of bfloat16 or fp16 is that it allows users in theory to easily improve the performance of their fp32 based code whilst minimizing the effort in porting code.
See this blog for more information on which use cases tf32(fp19) was aimed at https://blogs.nvidia.com/blog/2020/05/14/tensorfloat-32-precision-format/

2022-01-25 18:34 UTC, keryell commented
> However it could be argued that having these two different options could prove confusing to users. If it is preferred that we pick only one of these options then it would be better to make this decision sooner rather than later, since we plan on pushing fp19 support imminently.

Every thing should be hidden behind a normal C++ façade anyway so that if a user writes generic C++ it just works. It would be nice to have it using just 19 bits on FPGA and not moving internally useless 32 bits.

2022-01-26 11:02 UTC, JackAKirk commented
> > However it could be argued that having these two different options could prove confusing to users. If it is preferred that we pick only one of these options then it would be better to make this decision sooner rather than later, since we plan on pushing fp19 support imminently.
> 
> Every thing should be hidden behind a normal C++ façade anyway so that if a user writes generic C++ it just works. It would be nice to have it using just 19 bits on FPGA and not moving internally useless 32 bits.

That is interesting: For Nvidia GPU's fp19 uses 32 bit untyped as the storage type: See the bullet point **tf32 data format:** from https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#alternate-floating-point-data-formats.

I have noted that the mentions of fp19/bfloat19 that I could find in relation to Intel hardware were for FPGAs.  So am I correct in understanding from your comment that Intel FPGAs can support a native 19 bit data type and that, unlike Nvidia GPUs, do not make use of 32 bits as a storage type for fp19?
Then, are there are no cases of the fp19 "data format" stored in 32 bit storage type on any Intel hardware?

If this is the case then I would not worry about compatibility of Nvidia tf32 with Intel fp19, instead I would make an Nvidia backend only extension to support this tf32 variant of the fp19 data type which uses a 32 bit storage type.

2022-02-17 10:10 UTC, JackAKirk commented
Note: we have decided to put this PR on hold until we decide whether it is the correct way to use fp19.

2022-03-02 17:11 UTC, closed without merging