[SYCL] mode where only last command in each batch yields a host-visible event
intel/llvm pull request #5354
Opened 2022-01-20 23:01 UTC by smaslov-intel

Signed-off-by: Sergey V Maslov <sergey.v.maslov@intel.com>

2022-01-20 23:02 UTC, smaslov-intel commented
/sumamry:run

2022-01-21 20:48 UTC, smaslov-intel commented
/summary:run

2022-01-24 21:32 UTC, againull reviewed
Could you please update SYCL_PI_LEVEL_ZERO_DEVICE_SCOPE_EVENTS description in the documentation https://github.com/intel/llvm/blob/sycl/sycl/doc/EnvironmentVariables.md

Could you please add a feature test to llvm-test-suite and verify it with this PR.

2022-01-25 01:24 UTC, pvchupin requested changes

2022-01-25 01:24 UTC, pvchupin commented on sycl/doc/EnvironmentVariables.md
> +#Environment Variables
It breaks formatting.

2022-01-25 01:24 UTC, pvchupin commented on sycl/doc/EnvironmentVariables.md
> +`BackendName:XXX,DeviceType:YYY,DeviceVendorId:0xXYZW,DriverVersion:{
What's the purpose of this change?

2022-01-25 01:41 UTC, smaslov-intel commented on sycl/doc/EnvironmentVariables.md
> +}`.
```suggestion
`BackendName:XXX,DeviceType:YYY,DeviceVendorId:0xXYZW,DriverVersion:{{X.Y.Z.W}}`.
}`.
```

2022-01-25 01:42 UTC, smaslov-intel commented on sycl/doc/EnvironmentVariables.md
> +`BackendName:XXX,DeviceType:YYY,DeviceVendorId:0xXYZW,DriverVersion:{
ask clang-format )

2022-01-25 01:42 UTC, smaslov-intel commented on sycl/doc/EnvironmentVariables.md
> +}`.
```suggestion
`BackendName:XXX,DeviceType:YYY,DeviceVendorId:0xXYZW,DriverVersion:{{X.Y.Z.W}}`.
```

2022-01-25 01:43 UTC, smaslov-intel commented on sycl/doc/EnvironmentVariables.md
> +#Environment Variables
```suggestion
# Environment Variables
```

2022-01-25 01:44 UTC, pvchupin approved these changes
doc ok

2022-01-25 18:19 UTC, againull approved these changes

2022-01-25 18:19 UTC, merged