testing only
intel/llvm pull request #5358
Opened 2022-01-21 13:34 UTC by alexbatashev

2022-02-05 06:25 UTC, alexbatashev commented on sycl/include/CL/sycl/detail/pi.h
> +
```suggestion
```

2022-02-05 06:25 UTC, alexbatashev commented on sycl/source/CMakeLists.txt
> +  # add_dependencies(sycl libsycldevice)
```suggestion
  add_dependencies(sycl libsycldevice)
```

2022-02-09 11:28 UTC, romanovvlad requested changes

2022-02-09 11:28 UTC, romanovvlad commented on sycl/unittests/helpers/PiMock.cpp
> +        return redefinedPlatformsGet(0, num_entries, platforms, num_platforms);
Can we introduce some constexpr variable instead of using numbers(`0`) here?

2022-02-09 11:28 UTC, romanovvlad commented on sycl/unittests/helpers/include/helpers/sycl_test.hpp
> +    }
Shouldn't we delete default contexts?

2022-02-09 11:28 UTC, romanovvlad commented on sycl/unittests/helpers/include/helpers/PiMock.hpp
> +void redefineOne(const typename PiFuncType<PiKind>::type &F) {
It seems we often need to add a very simple logic like counting number of calls or checking if one of the arguments is correct. While this is not too difficult to redefine some of the APIs, there are set of APIs which would would require copy-pasting of default redefine body + a couple of lines to specific kernel needs.

So, the suggestion is to add something like append or prepend functionality, so a user(test writer) can provide a function which runs in addition(before or after) the function[s] which are already set for an API.

2022-09-08 02:16 UTC, closed without merging