[SYCL][ESIMD][EMU] Checking header files required for CM_EMU build
intel/llvm pull request #5365
Opened 2022-01-21 22:11 UTC by dongkyunahn-intel

This PR is for checking header files required for CM_EMU build. If check fails, configuration process terminates with messages for follow-up.

2022-01-21 23:50 UTC, kbobrovs commented
Per discussion with @pvchupin, let's disable building emulator by default, instead add a flag `--enable-esimd-emulator` which will be used by CI to enable it during precommits, similarly to how CUDA part is tested.

2022-01-21 23:54 UTC, kbobrovs commented
... but this check in the CMake files should remain and get exercised when emulator build is enabled

2022-01-25 07:35 UTC, vladimirlaz requested changes

2022-01-25 07:35 UTC, vladimirlaz commented on sycl/CMakeLists.txt
> +        message(FATAL_ERROR
Can the message contain a missing file to let the developer fix the issue?

2022-03-22 19:13 UTC, dongkyunahn-intel commented
LibVA dependency will be removed in CM_EMU. Closing this PR.

2022-03-22 19:13 UTC, closed without merging