[SYCL][ESIMD][EMU] Preventing 'cmrt_dump.txt' generation from CM
intel/llvm pull request #5469
Opened 2022-02-03 19:05 UTC by dongkyunahn-intel

- CM library used by ESIMD_EMULATOR support generates 'cmrt_dump.txt'
file for debugging

- This patch prevents file generation

- https://github.com/intel/llvm/issues/5379

2022-02-03 22:16 UTC, dongkyunahn-intel commented
This patch removes following line, and CM library package is generated without debug support, which generates `cmrt_dump.txt`.

https://github.com/intel/cm-cpu-emulation/blob/3c9eb58b06b72d28de3015d23243f0fa594cdb31/common/emu_log.h#L35

2022-02-10 13:32 UTC, bader commented
@pvchupin, could you take a look, please?

2022-02-10 22:31 UTC, pvchupin commented
It requires detailed explanation in PR description what's going on here and why this change is needed.
It looks like we may have design problem over the full stack?
Tagging @kbobrovs

2022-02-10 22:32 UTC, pvchupin requested changes
Commented above.

2022-02-11 02:06 UTC, dongkyunahn-intel commented
@pvchupin ,

Until CM library package used by ESIMD_EMULATOR is provided as pre-built one, it needs to be built during intel/llvm toolchain build by downloading & building source files from https://github.com/intel/cm-cpu-emulation. The CMakeLists.txt file modified in this ticket takes care of CM library generation.

CM library package built during `esimd_emulator` PI module build is generated as debug build. This build configuration happens to leave empty `cmrt_dump.txt` file after kernel execution (https://github.com/intel/llvm/issues/5379). As it could take a while for open-source CM library to be updated to prevent debug file generation, I applied online-patching for CM library to be built as Release build. This PR is for the online-patching.

2022-02-11 12:22 UTC, lsatanov commented
@dongkyunahn-intel , @ozhdikhin  I  can make a release that ONLY fixes this problem.
Why to make more "hacks" instead?

2022-02-11 13:31 UTC, lsatanov commented
I'm to release CM EMU with this issue fixed shortly, so this change will not be needed.

2022-02-11 21:50 UTC, pvchupin commented
@dongkyunahn-intel , @lsatanov thank you. That would be the best approach imo.

2022-02-18 15:46 UTC, lsatanov commented
Issue fixed in this release: https://github.com/intel/cm-cpu-emulation/releases/tag/v2022-02-11

2022-02-25 02:12 UTC, dongkyunahn-intel commented
PR is posted for using up-to-date opensource CM_EMU - https://github.com/intel/llvm/pull/5668

2022-02-25 02:12 UTC, closed without merging