[CI] Enable more test configs in pre-commit
intel/llvm pull request #5677
Opened 2022-02-26 06:49 UTC by alexbatashev

2022-03-01 05:32 UTC, dongkyunahn-intel commented
For ESIMD_EMULATOR backend, following PR needs to be merged in intel/llvm-test-suite.

https://github.com/intel/llvm-test-suite/pull/869

2022-03-08 19:41 UTC, dongkyunahn-intel commented
intel/llvm-test-suite repo is updated, and ESIMD_EMULATOR backend tests pass as follows.
```
Testing Time: 322.11s
  Unsupported      : 43
  Passed           : 64
  Expectedly Failed: 38

4 warning(s) in tests
[100%] Built target check-sycl-ext_intel_esimd_emulator-gpu
Scanning dependencies of target check-sycl-all
[100%] Built target check-sycl-all
```

2022-03-09 08:09 UTC, bader requested changes

2022-03-09 08:09 UTC, bader commented on devops/test_configs.json
> +    },
Please, remove this from the PR. It's not used and effectively a dead code.

2022-03-09 08:10 UTC, alexbatashev commented on devops/test_configs.json
> +    },
```suggestion
```

2022-03-09 08:13 UTC, bader commented on devops/test_configs.json
> +      "check_sycl_all": "ext_intel_esimd_emulator:gpu,host",
```suggestion
      "check_sycl_all": "ext_intel_esimd_emulator:gpu",
```
Can we exclude host device from this run?

2022-03-09 09:22 UTC, bader submitted a review, later dismissed

2022-03-09 09:25 UTC, bader commented
NOTE: This PR conflicts with https://github.com/intel/llvm/pull/5758.

2022-03-09 19:53 UTC, dongkyunahn-intel commented
ESIMD_EMULATOR build fails because of a missing change in https://github.com/intel/llvm/pull/5729. I'll share its status here.

2022-03-09 20:04 UTC, dongkyunahn-intel commented
PR is posted for missing change - https://github.com/intel/llvm/pull/5767.

2022-03-10 08:34 UTC, bader commented
@alexbatashev, I think we need to update this patch to align with https://github.com/intel/llvm/pull/5758.

2022-03-11 00:46 UTC, dongkyunahn-intel commented
> ESIMD_EMULATOR build fails because of a missing change in #5729. I'll share its status here.

Fix is applied in origin/sycl.

2022-03-14 06:04 UTC, dongkyunahn-intel commented
'Unexpected passes' from ESIMD_EMULATOR will be resolved with https://github.com/intel/llvm-test-suite/pull/910. I'll ask for merging the PR to intel/llvm-test-suite to Konst or Vladimir.

2022-03-14 08:09 UTC, bader requested changes
Please, merge https://github.com/intel/llvm-test-suite/pull/910 first and re-run precommit testing to make sure it passes.

2022-03-15 23:19 UTC, dongkyunahn-intel commented
@alexbatashev , intel/llvm-test-suite is updated to eliminate 'Unexpected passes'. Please verify and merge.

2022-03-16 07:28 UTC, bader approved these changes

2022-03-16 08:34 UTC, merged