[BuildBot] Uplift GPU RT version for Linux CI Process
intel/llvm pull request #5798
Opened 2022-03-13 12:13 UTC by bb-sycl

Uplift GPU RT version for Linux to 22.10.22597

2022-03-18 10:48 UTC, bader requested changes
Please, resolve merge conflicts.

2022-03-21 01:49 UTC, yanfeng3721 commented
/summary:run

2022-03-22 06:11 UTC, yanfeng3721 approved these changes
LGTM

2022-03-22 08:10 UTC, bader approved these changes

2022-03-22 08:27 UTC, alexbatashev approved these changes

2022-03-22 08:39 UTC, merged