[SYCL][L0] Move command list cache usage under mutex
intel/llvm pull request #5874
Opened 2022-03-24 08:18 UTC by KseniyaTikhomirova

For the example of usage that may cause issue please refer to assert_in_simulteneous_kernels E2E test. n queues that are working on the same device and on default context will work with the same zeCompute/CopyCommandListCache without protection since mutexes for queues are different buwhile cache is the same.
Operator[] may trigger insertion and rehash so simulteneous access is not thread-safe. In this code cache is not prefilled and insertion is done on the first access for every unique ZeDevice what may end up with simulteneous write access and memory corruption

Signed-off-by: Tikhomirova, Kseniya <kseniya.tikhomirova@intel.com>

2022-03-28 09:28 UTC, KseniyaTikhomirova commented
/summary:run

2022-03-29 13:49 UTC, KseniyaTikhomirova commented
OCL failure - known failure, expecting https://github.com/intel/llvm-test-suite/pull/944
ESIMD failure is also not possible to be related since I did a small change in L0 plugin.

2022-03-29 16:08 UTC, smaslov-intel requested changes

2022-03-29 16:33 UTC, smaslov-intel commented on sycl/plugins/level_zero/pi_level_zero.cpp
> +    // unique ZeDevice.
> The first time we try to use command list cache for exact device, operator[] does insertion and use this command list cache in the following code

That's exactly that I think is wrong.
Instead we need the `if (ZeCommandListCache.size() > 0) {` to return false, and new true item is inserted to the cache (not default-initialized one).

2022-03-29 16:48 UTC, KseniyaTikhomirova commented on sycl/plugins/level_zero/pi_level_zero.cpp
> +    // unique ZeDevice.
but we still do not insert default initialized items into the command cache list for exact device.
Here we are creating the list for exact device, not inserting the items into it.

This operator[] does insertion to map for exact ZeDevice, the list is still empty.
  std::unordered_map<ze_device_handle_t, std::list<ze_command_list_handle_t>>
      ZeComputeCommandListCache;

2022-03-30 17:44 UTC, merged