[SYCL][ESIMD] Fix a compilation of mix of unnamed ESIMD and non ESIMD kernels
intel/llvm pull request #6557
Opened 2022-08-10 18:27 UTC by fineg74

The purpose of this PR is to fix an issue that leads to runtime exception when unnamed ESIMD and non ESIMD kernels are present.

2022-08-10 21:02 UTC, asudarsa commented on llvm/tools/sycl-post-link/ModuleSplitter.cpp
> +    if (isESIMDFunctionInCallChain(F1, Deps)) {
Is there a possibility to break out o this loop sooner?
Thanks

2022-08-15 17:15 UTC, kbobrovs commented
@fineg74, could you please describe what the actual problem is - why unnamed ESIMD kernels lead to this problem?

2022-08-16 21:00 UTC, kbobrovs commented
We should try to limit ESIMD specifics penetration into general-purpose tools like post-link. My suggestion would be to find the wrapper function and add 'sycl_explicit_simd' metadata to it before doing any splits in the post-link. I believe the wrapper should have `spir_kernel` calling convention, which automatically makes it an entry point. The task of finding the wrapper(s) is then searching for all `spir_kernel`s up the call chain. ESIMD splitting and lowering infra will then correctly interpret the 'sycl_explicit_simd' metadata and do what's needed.

If the wrapper does not have `spir_kernel` (and is a `spir_function`), then the user ESIMD kernel must be annotated with `spir_kernel`. In which case the search for the wrapper would be finding terminal function in the callgraph starting from the user kernel up the call chain. Callgraph traversal up the call chain is implemented in ESIMDUtils.cpp (`traverseCallgraphUp`). In this case (no `spir_kernel` in the wrapper), we should also force the wrapper to be an entry point by copying the "sycl_module_id" attribute from the user kernel or creating a dummy one.

2022-08-16 21:03 UTC, kbobrovs commented
... I would suggest to implement finding the wrapper and adding the metadata as a pass defined within the llvm/lib/SYCLLowerIR directory and invoked in sycl-post-link.cpp somewhere around (and similarly to) the `const bool InvokeSimdMet = runModulePass<SYCLLowerInvokeSimdPass>(*M);`

2022-08-18 14:14 UTC, asudarsa submitted a review, later dismissed
sycl-post-link change looks good. Thanks

2022-08-18 18:00 UTC, kbobrovs requested changes

2022-08-18 18:00 UTC, kbobrovs commented on llvm/lib/SYCLLowerIR/ESIMD/LowerESIMDKernelAttrs.cpp
> +      llvm::esimd::traverseCallgraphUp(&F, [&](Function *GraphNode) {
BTW, is the wrapper function a `spir_kernel` or `spir_function`? Is the user function  a `spir_kernel` or `spir_function` in presence of wrapper?

2022-08-19 03:02 UTC, kbobrovs commented on llvm/include/llvm/SYCLLowerIR/ESIMD/LowerESIMD.h
> +class SYCLFixupESIMDKernelWrapperAttrPass
Not a good name either, my bad. As I noted, sycl_explicit_simd is a metadata. So please rename once again - `SYCLFixupESIMDKernelWrapperMDPass`. We need another iteration anyways.

2022-08-19 03:02 UTC, kbobrovs commented on llvm/lib/Passes/PassRegistry.def
> +FUNCTION_ANALYSIS("should-not-run-function-passes", ShouldNotRunFunctionPassesAnalysis())
unrelated changes

2022-08-19 22:13 UTC, kbobrovs approved these changes

2022-08-20 00:19 UTC, kbobrovs commented on llvm/lib/SYCLLowerIR/ESIMD/LowerESIMDKernelAttrs.cpp
> +      llvm::esimd::traverseCallgraphUp(&F, [&](Function *GraphNode) {
For the record: as we talked, the user function is `spir_func`, which is called by two kernels with `spir_kernel` CC - the normal and the one with the rounded range.

2022-08-24 02:23 UTC, asudarsa approved these changes
Changes look good. Thanks.

2022-08-25 17:06 UTC, merged