[SYCL-MLIR]: constructAttributeList returns CallingConv
intel/llvm pull request #7339
Opened 2022-11-09 20:31 UTC by etiotto

This PR modifies `constructAttributeList` to pass CallingConv as a reference argument (same as clang). The PR also applies a few clang-tidy related changes.

2022-11-09 20:36 UTC, etiotto commented on polygeist/tools/cgeist/Lib/CGCall.cc
> +  mlir::FunctionType FnType = ToCall.getFunctionType();
Just NFC changes.

2022-11-09 20:36 UTC, etiotto commented on polygeist/tools/cgeist/Lib/CGCall.cc
> -  llvm::errs() << "do not support indirecto call of " << Tocall << "\n";
Dead code

2022-11-09 20:36 UTC, etiotto commented on polygeist/tools/cgeist/Lib/CGCall.cc
> +    LLVM_DEBUG(if (!Obj.val) {
NFC changes

2022-11-09 20:36 UTC, etiotto commented on polygeist/tools/cgeist/Lib/CGExpr.cc
> +  auto ToCall = cast<func::FuncOp>(Glob.GetOrCreateMLIRFunction(F, ShouldEmit));
NFC changes

2022-11-09 20:36 UTC, etiotto commented on polygeist/tools/cgeist/Lib/CodeGenTypes.cc
> -  unsigned CC = FI.getEffectiveCallingConvention();
Caller will set calling convention (same as clang).

2022-11-09 20:36 UTC, etiotto commented on polygeist/tools/cgeist/Lib/clang-mlir.cc
> +      attrBuilder.addAttribute(
Used to be set in `constructAttributeList`, that function should only produce information (not change the IR).

2022-11-09 20:48 UTC, whitneywhtsang commented on polygeist/tools/cgeist/Lib/CGCall.cc
> +    LLVM_DEBUG(if (!Obj.val) {
Please add `{}` inside `LLVM_DEBUG()`.

2022-11-10 09:20 UTC, victor-eds requested changes

2022-11-10 09:20 UTC, victor-eds commented on polygeist/tools/cgeist/Lib/CGExpr.cc
> +    Args.push_back(std::make_pair(Visit(A), A));
```suggestion
  SmallVector<std::pair<ValueCategory, clang::Expr *>> Args{{obj, nullptr}};
  Args.reserve(cons->getNumArgs() + 1);
  for (auto A : cons->arguments())
    Args.emplace_back(Visit(A), A);
```

2022-11-10 15:41 UTC, etiotto commented on polygeist/tools/cgeist/Lib/CGCall.cc
> +    LLVM_DEBUG(if (!Obj.val) {
I like the way it looks now.

2022-11-10 16:11 UTC, etiotto commented on polygeist/tools/cgeist/Lib/CGCall.cc
> +    LLVM_DEBUG(if (!Obj.val) {
done

2022-11-10 16:14 UTC, whitneywhtsang approved these changes

2022-11-10 16:36 UTC, victor-eds approved these changes

2022-11-10 17:00 UTC, etiotto commented
@whitneywhtsang has added the parallel_for.cpp test to the LLVM test suite, that test is failing but is not a new failure. PR #7342 should make that test pass. Committing this one anyway because it is not breaking an existing working test.

2022-11-10 17:00 UTC, merged