[SYCL-MLIR] Rename SYCLConstructorOp and SYCLCallOp attributes
intel/llvm pull request #7387
Opened 2022-11-14 17:21 UTC by victor-eds

Rename SYCLConstructorOp's and SYCLCallOp's MangledName and SYCLCallOp's Function attribute to MangledFunctionName and FunctionName respectively to follow naming rules for the rest of the operations.

Rename SYCLCallOp's Type attribute to TypeName to avoid overlaps, as Type is already in use; and follow naming conventions.

Signed-off-by: Victor Perez <victor.perez@codeplay.com>

2022-11-14 17:23 UTC, victor-eds commented on mlir-sycl/include/mlir/Dialect/SYCL/IR/SYCLOps.td
> +    OptionalAttr<FlatSymbolRefAttr>:$TypeName,
This lead to warnings in this file.

2022-11-15 01:08 UTC, whitneywhtsang approved these changes

2022-11-15 01:09 UTC, whitneywhtsang requested changes
Please fix `convertToLLVMABI.mlir` lit failure.

2022-11-15 15:29 UTC, whitneywhtsang approved these changes

2022-11-15 15:53 UTC, etiotto approved these changes
LGTM

2022-11-15 16:05 UTC, merged