[SYCL-MLIR] Add sycl::vec support in the SYCL dialect
intel/llvm pull request #7432
Opened 2022-11-17 13:13 UTC by victor-eds

Add parsing, printing and lowering support for `sycl::vec`.

Signed-off-by: Victor Perez <victor.perez@codeplay.com>

2022-11-17 13:14 UTC, victor-eds commented
First of a PR series on supporting `sycl::vec`.

2022-11-17 13:15 UTC, victor-eds commented on mlir-sycl/include/mlir/Dialect/SYCL/IR/SYCLOpsTypes.h
> +  int NumElements;
Chose `int` as this is the type used in the template.

2022-11-17 17:34 UTC, etiotto approved these changes

2022-11-18 00:45 UTC, whitneywhtsang requested changes

2022-11-18 00:45 UTC, whitneywhtsang commented on mlir-sycl/test/Conversion/SYCLToLLVM/sycl-types-to-llvm.mlir
> +  func.func @test_vec(%arg0: !sycl.vec<[f32, 4], (vector<4xf32>)>) {
Missing check line.

2022-11-18 00:45 UTC, whitneywhtsang commented on mlir-sycl/test/Dialect/IR/SYCL/types.mlir
> +
```suggestion

// -----

```

2022-11-18 14:40 UTC, whitneywhtsang approved these changes

2022-11-18 14:46 UTC, merged