[SYCL-MLIR] Represent `sycl.id` and `sycl.range` with body `sycl.array`
intel/llvm pull request #7614
Opened 2022-12-01 23:30 UTC by whitneywhtsang

`sycl::id<1>` is lowered to `!llvm.struct<"class.sycl::_V1::id.1", (struct<"class.sycl::_V1::detail::array.1", (array<1 x i64>)>)>` in LLVM.
`sycl::range<1>` is lowered to `!llvm.struct<"class.sycl::_V1::range.1", (struct<"class.sycl::_V1::detail::array.1", (array<1 x i64>)>)>` in LLVM.

In MLIR, `sycl::id<1>` was represented as `!sycl.id<1>`,
`sycl::id<1>` is now represented as `!sycl_id_1_ = !sycl.id<[1], (!sycl.array<[1], (memref<1xi64, 4>)>)>` in this PR.
In MLIR, `sycl::range<1>` was represented as `!sycl.range<1>`,
`sycl::id<1>` is now represented as `!sycl_range_1_ = !sycl.range<[1], (!sycl.array<[1], (memref<1xi64, 4>)>)>` in this PR.
The benefit is we can have a more consistent implementation in `SYCLToLLVM` conversion, and before converting to LLVM, pass is aware that `sycl.id` and `sycl.range` contain `sycl.array`.

Signed-off-by: Tsang, Whitney <whitney.tsang@intel.com>

2022-12-01 23:36 UTC, etiotto commented
Nice explanation in the description. +1

2022-12-01 23:44 UTC, etiotto commented on mlir-sycl/lib/Conversion/SYCLToLLVM/SYCLToLLVM.cpp
> +  auto structTy = LLVM::LLVMStructType::getIdentified(
The getArrayTy was inlined (and removed) because was only used here.

2022-12-02 10:14 UTC, victor-eds reviewed
This is a welcome change. However, I was wondering whether we should have this attribute called a different way, e.g., `Bases`. What do you think? I don't have a strong opinion, though.

2022-12-02 15:13 UTC, whitneywhtsang commented
> This is a welcome change. However, I was wondering whether we should have this attribute called a different way, e.g., `Bases`. What do you think? I don't have a strong opinion, though.

Let's keep using `body` until we find a need? so we can reuse all the code with `body`.

2022-12-02 15:36 UTC, etiotto approved these changes

2022-12-02 15:52 UTC, victor-eds approved these changes

2022-12-02 15:56 UTC, victor-eds requested changes

2022-12-02 15:56 UTC, victor-eds commented on mlir-sycl/include/mlir/Dialect/SYCL/IR/SYCLOps.td
> +                        "llvm::SmallVector<mlir::Type, 4>":$body);
As I'll merge the commit now, you should use ArrayRefParameter<"mlir::Type"> here

2022-12-02 15:56 UTC, victor-eds commented on mlir-sycl/include/mlir/Dialect/SYCL/IR/SYCLOps.td
> +                        "llvm::SmallVector<mlir::Type, 4>":$body);
Same here

2022-12-02 15:56 UTC, victor-eds commented
LGTM after comment

2022-12-02 16:28 UTC, victor-eds commented
#7606 merged

2022-12-02 16:35 UTC, whitneywhtsang commented
> #7606 merged

Resolving merge conflict.

2022-12-02 19:00 UTC, merged