[SYCL][XPTI] Fix building with XPTI disabled
intel/llvm pull request #7898
Opened 2023-01-02 15:53 UTC by npmiller

The `XPTIScope` class uses some XPTI types, but the XPTI header is only included if the XPTI tracing is enabled, so when the XPTI tracing is disabled it fails to build.

So this patch simply macros out the whole `XPTIScope` class rather than specific member functions.

All the uses of `XPTIScope` in the codebase are already guarded by the macro.

2023-01-02 18:36 UTC, tovinkere requested changes
This specific change in 'xpti_registry.hpp' looks good!

However, there may be another place where I think there's a small issue as well:

> https://github.com/intel/llvm/blob/sycl/sycl/plugins/level_zero/tracing.cpp#L9
> https://github.com/intel/llvm/blob/sycl/sycl/plugins/level_zero/tracing.cpp#L12

They need to be under the same #if XPTI_ENABLE_INSTRUMENTATION like it is in done for the Cuda plugin.  Can that be made a part of this patch if you can confirm that would cause a failure as well?

2023-01-03 11:05 UTC, npmiller commented
Very good catch!

I was a little confused about it at first, because it turns out that when the xpti LLVM project is enabled, it copies its headers into `build/include`, and so even with support disabled in SYCL the xpti headers were still on the search path and so the plugin would still build.

But I can confirm that disabling the xpti project altogether as well as disabling SYCL support causes a build issue for the Level Zero plugin, I've added a patch to add the ifdef guards as suggested.

2023-01-03 17:11 UTC, tovinkere approved these changes
LGTM

2023-01-03 17:12 UTC, smaslov-intel approved these changes

2023-01-24 15:33 UTC, npmiller commented
friendly ping @intel/llvm-reviewers-runtime

2023-02-22 15:56 UTC, tovinkere approved these changes
LGTM

2023-02-22 15:57 UTC, tovinkere approved these changes
LGTM

2023-02-23 11:37 UTC, npmiller commented
ping @intel/llvm-reviewers-runtime @bso-intel @intel/llvm-gatekeepers 

Could we get some help with this PR, the build is currently broken with XPTI disabled.

2023-02-23 11:40 UTC, dm-vodopyanov approved these changes

2023-02-23 11:41 UTC, merged