[SYCL-MLIR][NFC]: Refactor CanonicalizeFor.cpp
intel/llvm pull request #8863
Opened 2023-03-29 19:43 UTC by etiotto

2023-03-29 23:23 UTC, whitneywhtsang requested changes

2023-03-29 23:23 UTC, whitneywhtsang commented on polygeist/lib/Dialect/Polygeist/Transforms/CanonicalizeFor.cpp
> +#include "mlir/Pass/Pass.h"
Why do we need new include?

2023-03-30 14:23 UTC, etiotto commented on polygeist/lib/Dialect/Polygeist/Transforms/CanonicalizeFor.cpp
> +      if (!isYieldOK(elseYieldOp))
fixed, ty!

2023-03-30 14:48 UTC, victor-eds commented on polygeist/lib/Dialect/Polygeist/Transforms/CanonicalizeFor.cpp
> -using namespace polygeist;
Oh, okey. Any option is fine with me!

2023-03-30 15:24 UTC, whitneywhtsang approved these changes

2023-03-30 16:20 UTC, merged