[SYCL] Support bool type for vec
intel/llvm pull request #8943
Opened 2023-04-04 13:23 UTC by Mikolaj-Filar-Mobica

This fixes #8543 
Before the change conversion like below was not possible:
`vec<bool, 4> __1 = vec<int, 4>{1, 1, 0, 0}.convert<bool>();`

2023-04-26 16:47 UTC, AlexeySachkov commented
@intel/sycl-language-enabling-triage: FYI

2023-04-27 14:45 UTC, jzc requested changes
These changes modify the definition of is_sgeninteger, and an ambiguity of partial template specialization is introduced for vec<bool, N>. 

```c++
// Multiple element bool
template <int N>
struct VecStorage<bool, N, typename std::enable_if_t<isValidVectorSize(N)>> {
  using DataType =
      typename VecStorageImpl<select_apply_cl_t<bool, std::int8_t, std::int16_t,
                                                std::int32_t, std::int64_t>,
                              N>::DataType;
};
[...]
// Multiple elements signed/unsigned integers and floating-point (except half)
template <typename T, int N>
struct VecStorage<T, N,
                  typename std::enable_if_t<isValidVectorSize(N) &&
                                            (is_sgeninteger<T>::value ||
                                             (is_sgenfloat<T>::value &&
                                              !is_half<T>::value))>> {
```

I think you want to modify that second specialization to be disabled with bool. Also, can you add tests for this? You can use sycl/test/basic_tests/vectors/vectors.cpp.

2023-04-28 06:51 UTC, Mikolaj-Filar-Mobica commented
> I think that this change may not be needed anymore since #8942 resolves #8543. The conversions should now work with `sycl::vec<bool, N>` types.

Thanks for your comment! Has anyone verified this? I have no time right now :( . If it's true, then the PR is indeed not needed.

2023-04-28 09:07 UTC, maarquitos14 commented
> I think that this change may not be needed anymore since #8942 resolves #8543. The conversions should now work with `sycl::vec<bool, N>` types.

I quickly tested the code in #8543 with #8942 changes included and it all works for me, so I agree that these changes shouldn't be required anymore.

2023-04-28 09:17 UTC, maarquitos14 commented
@Mikolaj-Filar-Mobica thank you for the contribution! It seems this is not required anymore, so I'm closing the PR.

2023-04-28 09:17 UTC, closed without merging

2023-04-28 13:55 UTC, Mikolaj-Filar-Mobica commented
> @Mikolaj-Filar-Mobica thank you for the contribution! It seems this is not required anymore, so I'm closing the PR.

Thank you!