[SYCL][Matrix] Disable sycl/test-e2e/Matrix/Legacy/element_wise_all_o…
intel/llvm pull request #9510
Opened 2023-05-18 05:15 UTC by yubingex007-a11y

…ps_int8_packed.cpp for cpu

2023-05-18 15:55 UTC, YuriPlyakhin requested changes

2023-05-18 15:55 UTC, YuriPlyakhin commented on sycl/test-e2e/Matrix/Legacy/element_wise_all_ops_int8_packed.cpp
> +// XFAIL: *
The test should pass on GPU with updated IGC. Should it be like that instead?
```suggestion
// XFAIL: cpu
```

2023-05-18 15:57 UTC, YuriPlyakhin commented
I don't know, if it should pass or fail on CPU. @dkhaldi , could you please confirm?

2023-05-18 19:24 UTC, dkhaldi commented
> I don't know, if it should pass or fail on CPU. @dkhaldi , could you please confirm?

If you look at https://github.com/intel/llvm/blob/sycl/sycl/test-e2e/Matrix/Legacy/element_wise_all_ops_int8_packed_impl.hpp
you will find statements like:
` joint_matrix_store(sg, sub_b,
                              accA.get_pointer() + (sg_startx * TM) * N * 4 +
                                  sg_starty / SG_SZ * TN * 4,
                              N * 4, matrix_layout::row_major);`

This is a store from sub_b that is in VNNI format to memory in row major. Currently, we dont support such store. The only store we can do is a store with packed as matrix layout.

That's why this test cannot pass on SPR (or on the GPU for that matter as the same limitation exist currently for the GPU implementation)

2023-05-19 15:27 UTC, aelovikov-intel commented
@dkhaldi , does it mean that you agree with this patch? If so, can you please formally approve it?

2023-05-19 20:06 UTC, dkhaldi approved these changes
LGTM

2023-05-19 20:22 UTC, aelovikov-intel approved these changes

2023-05-19 20:22 UTC, merged