[SYCL][CI] Use Self-build with Shared libs for post-commit testing
intel/llvm pull request #9655
Opened 2023-05-30 17:35 UTC by aelovikov-intel

Remove no-asserts build.

2023-05-30 18:20 UTC, bader requested changes
I think running tests with no assertions is important for the project.

2023-05-30 18:20 UTC, bader commented on .github/workflows/sycl_post_commit.yml
> +      build_configure_extra_args: --shared-libs --hip --cuda --enable-esimd-emulator --cmake-opt="-DSYCL_ENABLE_STACK_PRINTING=ON" --cmake-opt="-DSYCL_LIB_WITH_DEBUG_SYMBOL=ON"
```suggestion
      build_configure_extra_args: --shared-libs --hip --cuda --enable-esimd-emulator --cmake-opt="-DSYCL_ENABLE_STACK_PRINTING=ON" --cmake-opt="-DSYCL_LIB_WITH_DEBUG_SYMBOL=ON" --no-assertions
```

2023-05-30 18:57 UTC, bader approved these changes

2023-05-31 05:53 UTC, smaslov-intel approved these changes

2023-05-31 14:31 UTC, sergey-semenov approved these changes

2023-05-31 14:32 UTC, merged