[SYCL][CI] Use LZ4 compression for the toolchain artifact
intel/llvm pull request #9675
Opened 2023-05-31 15:48 UTC by aelovikov-intel

Start with Linux only for now.

2023-05-31 15:49 UTC, aelovikov-intel commented
I'm not sure if https://github.com/intel/llvm/blob/66b9e114326462eb4a7b67dccf36cca875b8791b/devops/containers/ubuntu2204_preinstalled.Dockerfile#L8 needs/can be changed as well.

2023-05-31 16:45 UTC, cperkinsintel approved these changes

2023-05-31 18:53 UTC, aelovikov-intel commented
> > Start with Linux only for now.
> 
> Please, expand on the benefits of using LZ4 in the PR description. What is the impact on pack/unpack time and the size of the archive?

Updated - I was waiting for the CI to finish to get the data.

2023-05-31 19:09 UTC, bader requested changes
Can you compare with the approach from https://github.com/intel/llvm/pull/5678?
I think there are high chances we hit the GitHub storage limit as lz4 significantly increases the archive size.

2023-06-01 21:03 UTC, bader approved these changes

2023-06-02 03:20 UTC, merged