Xpti usm diagnostic
intel/llvm pull request #9840
Opened 2023-06-13 12:25 UTC by KseniyaTikhomirova

2023-06-21 00:03 UTC, tovinkere requested changes
Need clarification on trace types chosen in emitFunctionWithArgsBeginTrace()

2023-06-22 11:11 UTC, KseniyaTikhomirova commented
> sycl/source/detail/pi.cpp

@tovinkere could you please advise how to improve that? I need to add event for every call to be able to pass code_location (it could be properly passed only by event) and I took graph event. Would it be ok if I create new event type like "trace_diagnostic_event" as a general purpose event?

2023-06-27 16:44 UTC, KseniyaTikhomirova commented on sycl/source/detail/pi.cpp
> +        GPIArgCallEvent, GPIArgCallActiveEvent, CorrelationID, &Payload);
to check if we need to update xpti documentation

2023-06-29 09:39 UTC, KseniyaTikhomirova commented on sycl/source/detail/pi.cpp
> +        GPIArgCallEvent, GPIArgCallActiveEvent, CorrelationID, &Payload);
https://github.com/intel/llvm/pull/9840/commits/dbee52f5456e4aed56d60986abd2b49bb1f1ad9f

2023-06-29 16:14 UTC, tovinkere approved these changes
LGTM

2023-07-04 13:52 UTC, KseniyaTikhomirova commented
@tovinkere I added small fixes in https://github.com/intel/llvm/pull/9840/commits/5d58f894b81a4f817bb31d2d7296a5f8a4ebf74e. Could you please review it? (small change)

2023-07-04 15:25 UTC, KseniyaTikhomirova commented
Failed Tests (1):
SYCL :: ESIMD/accessor_local.cpp - Reported in https://github.com/intel/llvm/issues/10138.

2023-07-04 16:29 UTC, tovinkere reviewed
LGTM

2023-07-05 09:22 UTC, KseniyaTikhomirova commented
Unexpectedly Passed Tests (1):
SYCL :: DeviceArchitecture/device_architecture_on_host.cpp - Seems that our drivers on pre-commit machines are ready for this one to be enabled. Tag @dm-vodopyanov for awareness.

2023-07-05 09:22 UTC, KseniyaTikhomirova commented
@intel/llvm-gatekeepers hi, this PR is ready for merge

2023-07-05 09:45 UTC, dm-vodopyanov commented
> Unexpectedly Passed Tests (1): SYCL :: DeviceArchitecture/device_architecture_on_host.cpp - Seems that our drivers on pre-commit machines are ready for this one to be enabled. Tag @dm-vodopyanov for awareness.

https://github.com/intel/llvm/commit/a54d2a2c3039541351e9535303ca3d2a1f7f6f19

2023-07-05 09:47 UTC, dm-vodopyanov commented
> @intel/llvm-gatekeepers hi, this PR is ready for merge

Code owner review required
Waiting on code owner review from intel/llvm-reviewers-runtime.

2023-07-05 09:47 UTC, dm-vodopyanov approved these changes

2023-07-05 09:48 UTC, merged

2023-07-05 11:14 UTC, steffenlarsen commented
@KseniyaTikhomirova - This introduced some post-commit failures. Could you please address these ASAP?

2023-07-05 11:47 UTC, KseniyaTikhomirova commented
https://github.com/intel/llvm/pull/10206 should fix post commit